#pragma once

namespace fallout {

enum class GameGlobalVar : int {
    GVAR_CHILD_KILLER_SHADY = 0,
    GVAR_CHILD_KILLER_HUB = 1,
    GVAR_NUM_RADSCORPIONS = 2,
    GVAR_CHILD_KILLER_ADYTUM = 3,
    GVAR_DOGS_KILLED = 4,
    GVAR_DOG_EMPATHY = 5,
    GVAR_QUEST_PEOPLE = 6,
    GVAR_FOLLOWERS_INVADED = 7,
    GVAR_MAP_ENTRANCE_NUMBER = 8,
    GVAR_DAYS_TO_VAULT13_DISCOVERY = 9,
    GVAR_VAULT_WATER = 10,
    GVAR_VAULT_INVADED = 11,
    GVAR_SHADY_SANDS_INVADED = 12,
    GVAR_NECROPOLIS_INVADED = 13,
    GVAR_HUB_INVADED = 14,
    GVAR_JUNKTOWN_INVADED = 15,
    GVAR_BROTHERHOOD_INVADED = 16,
    GVAR_VATS_BLOWN = 17,
    GVAR_MASTER_BLOWN = 18,
    GVAR_NECROPOLIS_VISITED = 19,
    GVAR_NECROPOLIS_KNOWN = 20,
    GVAR_MOTEL_OF_DOOM_VISITED = 21,
    GVAR_HALL_OF_THE_DEAD_VISITED = 22,
    GVAR_WATERSHED_VISITED = 23,
    GVAR_NECROPOLIS_VAULT_VISITED = 24,
    GVAR_TANDI_X = 25,
    GVAR_TANDI_STATUS = 26,
    GVAR_TANDI_DEAD = 27,
    GVAR_RADSCORPIONS_KILLED = 28,
    GVAR_NECROP_MUTANTS_KILLED = 29,
    GVAR_NECROP_WATER_CHIP_TAKEN = 30,
    GVAR_NECROP_WATER_PUMP_FIXED = 31,
    GVAR_LOAD_MAP_INDEX = 32,
    GVAR_ANIMALS_KILLED = 33,
    GVAR_HUMANS_KILLED = 34,
    GVAR_SUPER_MUTANTS_KILLED = 35,
    GVAR_HIRED_BY_KILLIAN = 36,
    GVAR_KILLIAN_DEAD = 37,
    GVAR_GIZMO_DEAD = 38,
    GVAR_HIRED_BY_GIZMO = 39,
    GVAR_IN_JAIL = 40,
    GVAR_BUG_PLANTED = 41,
    GVAR_GOT_CONFESSION = 42,
    GVAR_RADSCORPION_SEED = 43,
    GVAR_DEATHCLAW_SEED = 44,
    GVAR_BROTHERHOOD_SEED = 45,
    GVAR_HUB_SEED = 46,
    GVAR_PLAYER_LOCATION = 47,
    GVAR_LOXLEY_X = 48,
    GVAR_MAXSON_X = 49,
    GVAR_CATHEDRAL = 50,
    GVAR_VATS_STATUS = 51,
    GVAR_CHILDREN_STATUS = 52,
    GVAR_MASTER_DEAD = 53,
    GVAR_LIEUTENANTS_DEAD = 54,
    GVAR_COUNTDOWN_TO_DESTRUCTION = 55,
    GVAR_BOMB_DISARMED = 56,
    GVAR_ENTERING_VATS_HOW = 57,
    GVAR_WATER_SHED_STATUS = 58,
    GVAR_PLAYER_CAPTURED = 59,
    GVAR_SIGNAL_REWARD = 60,
    GVAR_SHADOW_PASSWORD = 61,
    GVAR_FOLLOWER_STEALTH_HELP = 62,
    GVAR_FOLLOWER_MACHO_HELP = 63,
    GVAR_KNIGHT_WARNING = 64,
    GVAR_WORLD_TERRAIN = 65,
    GVAR_NECROP_WATER = 66,
    GVAR_VAULT_13 = 67,
    GVAR_SHADY_SANDS = 68,
    GVAR_RAIDERS = 69,
    GVAR_BURIED_VAULT = 70,
    GVAR_JUNKTOWN = 71,
    GVAR_NECROPOLIS = 72,
    GVAR_THE_HUB = 73,
    GVAR_BROTHERHOOD_OF_STEEL = 74,
    GVAR_ANGELS_BONEYARD = 75,
    GVAR_THE_GLOW = 76,
    GVAR_CHILDREN_OF_CATHEDRAL = 77,
    GVAR_THE_VATS = 78,
    GVAR_MASTERS_LAIR = 79,
    GVAR_BROTHERHOOD_12 = 80,
    GVAR_BROTHERHOOD_34 = 81,
    GVAR_BROTHERHOOD_ENTRANCE = 82,
    GVAR_CAVES = 83,
    GVAR_CHILDREN_1 = 84,
    GVAR_DESERT_1 = 85,
    GVAR_DESERT_2 = 86,
    GVAR_DESERT_3 = 87,
    GVAR_HALL_OF_THE_DEAD = 88,
    GVAR_HOTEL_OF_DOOM = 89,
    GVAR_JUNKTOWN_CASINO = 90,
    GVAR_JUNKTOWN_ENTRANCE = 91,
    GVAR_JUNKTOWN_KILLIAN = 92,
    GVAR_SHADY_SANDS_EAST = 93,
    GVAR_SHADY_SANDS_WEST = 94,
    GVAR_VAULT_13_MAP = 95,
    GVAR_BURIED_VAULT_MAP = 96,
    GVAR_VAULT_ENTRANCE = 97,
    GVAR_NECROP_VAULT = 98,
    GVAR_WATERSHED = 99,
    GVAR_KILL_DEATHCLAW = 100,
    GVAR_FIND_WATER_CHIP = 101,
    GVAR_KILL_RADSCORPIONS = 102,
    GVAR_RESCUE_TANDI = 103,
    GVAR_CAPTURE_GIZMO = 104,
    GVAR_KILL_KILLIAN = 105,
    GVAR_MISSING_CARAVAN = 106,
    GVAR_STEAL_NECKLACE = 107,
    GVAR_BECOME_AN_INITIATE = 108,
    GVAR_FIND_LOST_INITIATE = 109,
    GVAR_WARNED_BROTHERHOOD = 110,
    GVAR_KILL_MERCHANT = 111,
    GVAR_KILL_JAIN = 112,
    GVAR_KILL_SUPER_MUTANTS = 113,
    GVAR_GARL_DEAD = 114,
    GVAR_TOTAL_RAIDERS = 115,
    GVAR_MISTAKEN_ID = 116,
    GVAR_WITH_CARAVAN = 117,
    GVAR_IAN_STATUS = 118,
    GVAR_TOLYA_STATUS = 119,
    GVAR_PETROX_STATUS = 120,
    GVAR_HERNANDEZ_STATUS = 121,
    GVAR_KENJI_STATUS = 122,
    GVAR_HUNTER_STATUS = 123,
    GVAR_SETH_STATUS = 124,
    GVAR_TRENT_STATUS = 125,
    GVAR_JASON_STATUS = 126,
    GVAR_ROMEO_JULIET = 127,
    GVAR_GANG_WAR = 128,
    GVAR_DESTROY_FOLLOWERS = 129,
    GVAR_LOST_BROTHER = 130,
    GVAR_BLADES_HELP = 131,
    GVAR_TRAIN_FOLLOWERS = 132,
    GVAR_FIND_AGENT = 133,
    GVAR_TANGLER_DEAD = 134,
    GVAR_BECOME_BLADE = 135,
    GVAR_BLADES_LEFT = 136,
    GVAR_RIPPERS_LEFT = 137,
    GVAR_FIX_FARM = 138,
    GVAR_START_POWER = 139,
    GVAR_WEAPONS_ARMED = 140,
    GVAR_FOUND_DISK = 141,
    GVAR_WEAPON_LOCKER = 142,
    GVAR_SAVE_SINTHIA = 143,
    GVAR_SAUL_QUEST = 144,
    GVAR_TRISH_QUEST = 145,
    GVAR_VATS_ALERT = 146,
    GVAR_VATS_COUNTDOWN = 147,
    GVAR_FOLLOWERS_INVADED_DATE = 148,
    GVAR_NECROPOLIS_INVADED_DATE = 149,
    GVAR_THE_HUB_INVADED_DATE = 150,
    GVAR_BROTHERHOOD_INVADED_DATE = 151,
    GVAR_JUNKTOWN_INVADED_DATE = 152,
    GVAR_SHADY_SANDS_INVADED_DATE = 153,
    GVAR_VAULT_13_INVADED_DATE = 154,
    GVAR_PLAYER_REPUATION = 155,
    GVAR_BERSERKER_REPUTATION = 156,
    GVAR_CHAMPION_REPUTATION = 157,
    GVAR_CHILDKILLER_REPUATION = 158,
    GVAR_GOOD_MONSTER = 159,
    GVAR_BAD_MONSTER = 160,
    GVAR_ARTIFACT_DISK = 161,
    GVAR_FEV_DISK = 162,
    GVAR_SECURITY_DISK = 163,
    GVAR_ALPHA_DISK = 164,
    GVAR_DELTA_DISK = 165,
    GVAR_VREE_DISK = 166,
    GVAR_HONOR_DISK = 167,
    GVAR_RENT_TIME = 168,
    GVAR_SAUL_STATUS = 169,
    GVAR_GIZMO_STATUS = 170,
    GVAR_GANGS = 171,
    GVAR_GANG_BEGONE = 172,
    GVAR_GANG_1 = 173,
    GVAR_GANG_2 = 174,
    GVAR_FOOLS_SCOUT = 175,
    GVAR_FSCOUT_1 = 176,
    GVAR_CRYPTS_SCOUT = 177,
    GVAR_CSCOUT_1 = 178,
    GVAR_POWER = 179,
    GVAR_POWER_GENERATOR = 180,
    GVAR_GENERATOR_1 = 181,
    GVAR_GENERATOR_2 = 182,
    GVAR_GENERATOR_3 = 183,
    GVAR_PEASANTS = 184,
    GVAR_DOG_PHIL = 185,
    GVAR_DOG_1 = 186,
    GVAR_DOG_2 = 187,
    GVAR_WATER_THIEF = 188,
    GVAR_NUKA_COLA_ADDICT = 189,
    GVAR_BUFF_OUT_ADDICT = 190,
    GVAR_MENTATS_ADDICT = 191,
    GVAR_PSYCHO_ADDICT = 192,
    GVAR_RADAWAY_ADDICT = 193,
    GVAR_ALCOHOL_ADDICT = 194,
    GVAR_CATHEDRAL_ENEMY = 195,
    GVAR_MORPHEUS_KNOWN = 196,
    GVAR_KNOW_NIGHTKIN = 197,
    GVAR_PC_WANTED = 198,
    GVAR_CRIMSON_CARAVANS_STATUS = 199,
    GVAR_WATER_MERCHANTS_STATUS = 200,
    GVAR_FARGO_TRADERS_STATUS = 201,
    GVAR_UNDERGROUND_STATUS = 202,
    GVAR_DECKER_STATUS = 203,
    GVAR_CC_JOB = 204,
    GVAR_WATER_JOB = 205,
    GVAR_FARGO_JOB = 206,
    GVAR_Loxley_known = 207,
    GVAR_MARK_DEATHCLAW = 208,
    GVAR_MUTANT_DISK = 209,
    GVAR_BROTHER_HISTORY = 210,
    GVAR_SOPHIA_DISK = 211,
    GVAR_MAXSON_DISK = 212,
    GVAR_TANDI_ESCAPE = 213,
    GVAR_RAID_LOOTING = 214,
    GVAR_CVAN_DRIVER = 215,
    GVAR_CVAN_GUARD = 216,
    GVAR_TANDI_HEREBEFORE = 217,
    GVAR_TALKED_ABOUT_TANDI = 218,
    GVAR_DECKER_KNOWN = 219,
    GVAR_WANTED_FOR_MURDER = 220,
    GVAR_GREENE_DEAD = 221,
    GVAR_WANTED_THEFT = 222,
    GVAR_BROTHERHOOD_INVASION = 223,
    GVAR_GLOW_POWER = 224,
    GVAR_HUB_FILLER_28 = 225,
    GVAR_HUB_FILLER_29 = 226,
    GVAR_HUB_FILLER_30 = 227,
    GVAR_NUM_RADIO = 228,
    GVAR_RADIO_MISTAKE = 229,
    GVAR_CHANNEL_SLOT_DOWN = 230,
    GVAR_MASTER_FILLER_4 = 231,
    GVAR_MASTER_FILLER_5 = 232,
    GVAR_MASTER_FILLER_6 = 233,
    GVAR_MASTER_FILLER_7 = 234,
    GVAR_MASTER_FILLER_8 = 235,
    GVAR_MASTER_FILLER_9 = 236,
    GVAR_MASTER_FILLER_10 = 237,
    GVAR_CALM_REBELS = 238,
    GVAR_CURE_JARVIS = 239,
    GVAR_MAKE_ANTIDOTE = 240,
    GVAR_MORPHEUS_DELIVERS_PLAYER = 241,
    GVAR_DESTROY_VATS = 242,
    GVAR_DESTROY_MASTER = 243,
    GVAR_KATJA_STATUS = 244,
    GVAR_ENEMY_VAULT_13 = 245,
    GVAR_ENEMY_SHADY_SANDS = 246,
    GVAR_ENEMY_JUNKTOWN = 247,
    GVAR_ENEMY_HUB = 248,
    GVAR_ENEMY_NECROPOLIS = 249,
    GVAR_ENEMY_BROTHERHOOD = 250,
    GVAR_ENEMY_ADYTUM = 251,
    GVAR_ENEMY_RIPPERS = 252,
    GVAR_ENEMY_BLADES = 253,
    GVAR_ENEMY_RAIDERS = 254,
    GVAR_ENEMY_CATHEDRAL = 255,
    GVAR_ENEMY_FOLLOWERS = 256,
    GVAR_GENERIC_FILLER_20 = 257,
    GVAR_WATER_CHIP_1 = 258,
    GVAR_WATER_CHIP_2 = 259,
    GVAR_WATER_CHIP_3 = 260,
    GVAR_WATER_CHIP_4 = 261,
    GVAR_WATER_CHIP_5 = 262,
    GVAR_WATER_CHIP_6 = 263,
    GVAR_WATER_CHIP_7 = 264,
    GVAR_WATER_CHIP_8 = 265,
    GVAR_WATER_CHIP_9 = 266,
    GVAR_WATER_CHIP_10 = 267,
    GVAR_WATER_CHIP_11 = 268,
    GVAR_WATER_CHIP_12 = 269,
    GVAR_WATER_CHIP_13 = 270,
    GVAR_WATER_CHIP_14 = 271,
    GVAR_WATER_CHIP_15 = 272,
    GVAR_DESTROY_VATS_1 = 273,
    GVAR_DESTROY_VATS_2 = 274,
    GVAR_DESTROY_VATS_3 = 275,
    GVAR_DESTROY_VATS_4 = 276,
    GVAR_DESTROY_VATS_5 = 277,
    GVAR_DESTROY_VATS_6 = 278,
    GVAR_DESTROY_VATS_7 = 279,
    GVAR_DESTROY_VATS_8 = 280,
    GVAR_DESTROY_VATS_9 = 281,
    GVAR_DESTROY_VATS_10 = 282,
    GVAR_DESTROY_VATS_11 = 283,
    GVAR_DESTROY_VATS_12 = 284,
    GVAR_DESTROY_VATS_13 = 285,
    GVAR_DESTROY_VATS_14 = 286,
    GVAR_DESTROY_VATS_15 = 287,
    GVAR_WATER_THIEF_1 = 288,
    GVAR_WATER_THIEF_2 = 289,
    GVAR_WATER_THIEF_3 = 290,
    GVAR_WATER_THIEF_4 = 291,
    GVAR_WATER_THIEF_5 = 292,
    GVAR_WATER_THIEF_6 = 293,
    GVAR_WATER_THIEF_7 = 294,
    GVAR_WATER_THIEF_8 = 295,
    GVAR_WATER_THIEF_9 = 296,
    GVAR_WATER_THIEF_10 = 297,
    GVAR_CALM_REBELS_1 = 298,
    GVAR_CALM_REBELS_2 = 299,
    GVAR_CALM_REBELS_3 = 300,
    GVAR_CALM_REBELS_4 = 301,
    GVAR_CALM_REBELS_5 = 302,
    GVAR_CALM_REBELS_6 = 303,
    GVAR_CALM_REBELS_7 = 304,
    GVAR_DESTROY_MASTER_1 = 305,
    GVAR_DESTROY_MASTER_2 = 306,
    GVAR_DESTROY_MASTER_3 = 307,
    GVAR_DESTROY_MASTER_4 = 308,
    GVAR_DESTROY_MASTER_5 = 309,
    GVAR_DESTROY_MASTER_6 = 310,
    GVAR_DESTROY_MASTER_7 = 311,
    GVAR_DESTROY_MASTER_8 = 312,
    GVAR_DESTROY_MASTER_9 = 313,
    GVAR_DESTROY_MASTER_10 = 314,
    GVAR_DESTROY_MASTER_11 = 315,
    GVAR_DESTROY_MASTER_12 = 316,
    GVAR_DESTROY_MASTER_13 = 317,
    GVAR_DESTROY_MASTER_14 = 318,
    GVAR_DESTROY_MASTER_15 = 319,
    GVAR_STOP_SCORPIONS_1 = 320,
    GVAR_STOP_SCORPIONS_2 = 321,
    GVAR_STOP_SCORPIONS_3 = 322,
    GVAR_STOP_SCORPIONS_4 = 323,
    GVAR_STOP_SCORPIONS_5 = 324,
    GVAR_STOP_SCORPIONS_6 = 325,
    GVAR_STOP_SCORPIONS_7 = 326,
    GVAR_STOP_SCORPIONS_8 = 327,
    GVAR_STOP_SCORPIONS_9 = 328,
    GVAR_STOP_SCORPIONS_10 = 329,
    GVAR_SAVE_TANDI_1 = 330,
    GVAR_SAVE_TANDI_2 = 331,
    GVAR_SAVE_TANDI_3 = 332,
    GVAR_SAVE_TANDI_4 = 333,
    GVAR_SAVE_TANDI_5 = 334,
    GVAR_SAVE_TANDI_6 = 335,
    GVAR_SAVE_TANDI_7 = 336,
    GVAR_SAVE_TANDI_8 = 337,
    GVAR_SAVE_TANDI_9 = 338,
    GVAR_SAVE_TANDI_10 = 339,
    GVAR_CURE_JARVIS_1 = 340,
    GVAR_CURE_JARVIS_2 = 341,
    GVAR_CURE_JARVIS_3 = 342,
    GVAR_CURE_JARVIS_4 = 343,
    GVAR_CURE_JARVIS_5 = 344,
    GVAR_CURE_JARVIS_6 = 345,
    GVAR_CURE_JARVIS_7 = 346,
    GVAR_CURE_JARVIS_8 = 347,
    GVAR_CURE_JARVIS_9 = 348,
    GVAR_CURE_JARVIS_10 = 349,
    GVAR_MAKE_ANTIDOTE_1 = 350,
    GVAR_MAKE_ANTIDOTE_2 = 351,
    GVAR_MAKE_ANTIDOTE_3 = 352,
    GVAR_MAKE_ANTIDOTE_4 = 353,
    GVAR_MAKE_ANTIDOTE_5 = 354,
    GVAR_MAKE_ANTIDOTE_6 = 355,
    GVAR_MAKE_ANTIDOTE_7 = 356,
    GVAR_MAKE_ANTIDOTE_8 = 357,
    GVAR_MAKE_ANTIDOTE_9 = 358,
    GVAR_MAKE_ANTIDOTE_10 = 359,
    GVAR_KILL_MUTANTS_1 = 360,
    GVAR_KILL_MUTANTS_2 = 361,
    GVAR_KILL_MUTANTS_3 = 362,
    GVAR_KILL_MUTANTS_4 = 363,
    GVAR_KILL_MUTANTS_5 = 364,
    GVAR_KILL_MUTANTS_6 = 365,
    GVAR_KILL_MUTANTS_7 = 366,
    GVAR_KILL_MUTANTS_8 = 367,
    GVAR_KILL_MUTANTS_9 = 368,
    GVAR_KILL_MUTANTS_10 = 369,
    GVAR_FIX_NECROP_PUMP_1 = 370,
    GVAR_FIX_NECROP_PUMP_2 = 371,
    GVAR_FIX_NECROP_PUMP_3 = 372,
    GVAR_FIX_NECROP_PUMP_4 = 373,
    GVAR_FIX_NECROP_PUMP_5 = 374,
    GVAR_FIX_NECROP_PUMP_6 = 375,
    GVAR_FIX_NECROP_PUMP_7 = 376,
    GVAR_FIX_NECROP_PUMP_8 = 377,
    GVAR_FIX_NECROP_PUMP_9 = 378,
    GVAR_FIX_NECROP_PUMP_10 = 379,
    GVAR_KILL_KILLIAN_1 = 380,
    GVAR_KILL_KILLIAN_2 = 381,
    GVAR_KILL_KILLIAN_3 = 382,
    GVAR_KILL_KILLIAN_4 = 383,
    GVAR_KILL_KILLIAN_5 = 384,
    GVAR_KILL_KILLIAN_6 = 385,
    GVAR_KILL_KILLIAN_7 = 386,
    GVAR_KILL_KILLIAN_8 = 387,
    GVAR_KILL_KILLIAN_9 = 388,
    GVAR_KILL_KILLIAN_10 = 389,
    GVAR_STOP_GIZMO_1 = 390,
    GVAR_STOP_GIZMO_2 = 391,
    GVAR_STOP_GIZMO_3 = 392,
    GVAR_STOP_GIZMO_4 = 393,
    GVAR_STOP_GIZMO_5 = 394,
    GVAR_STOP_GIZMO_6 = 395,
    GVAR_STOP_GIZMO_7 = 396,
    GVAR_STOP_GIZMO_8 = 397,
    GVAR_STOP_GIZMO_9 = 398,
    GVAR_STOP_GIZMO_10 = 399,
    GVAR_SAVE_SINTHIA_1 = 400,
    GVAR_SAVE_SINTHIA_2 = 401,
    GVAR_SAVE_SINTHIA_3 = 402,
    GVAR_SAVE_SINTHIA_4 = 403,
    GVAR_SAVE_SINTHIA_5 = 404,
    GVAR_SAVE_SINTHIA_6 = 405,
    GVAR_SAVE_SINTHIA_7 = 406,
    GVAR_SAVE_SINTHIA_8 = 407,
    GVAR_SAVE_SINTHIA_9 = 408,
    GVAR_SAVE_SINTHIA_10 = 409,
    GVAR_TRISH_QUEST_1 = 410,
    GVAR_TRISH_QUEST_2 = 411,
    GVAR_TRISH_QUEST_3 = 412,
    GVAR_TRISH_QUEST_4 = 413,
    GVAR_TRISH_QUEST_5 = 414,
    GVAR_TRISH_QUEST_6 = 415,
    GVAR_TRISH_QUEST_7 = 416,
    GVAR_TRISH_QUEST_8 = 417,
    GVAR_TRISH_QUEST_9 = 418,
    GVAR_TRISH_QUEST_10 = 419,
    GVAR_SAUL_QUEST_1 = 420,
    GVAR_SAUL_QUEST_2 = 421,
    GVAR_SAUL_QUEST_3 = 422,
    GVAR_SAUL_QUEST_4 = 423,
    GVAR_SAUL_QUEST_5 = 424,
    GVAR_SAUL_QUEST_6 = 425,
    GVAR_SAUL_QUEST_7 = 426,
    GVAR_SAUL_QUEST_8 = 427,
    GVAR_SAUL_QUEST_9 = 428,
    GVAR_SAUL_QUEST_10 = 429,
    GVAR_STEAL_NECKLACE_1 = 430,
    GVAR_STEAL_NECKLACE_2 = 431,
    GVAR_STEAL_NECKLACE_3 = 432,
    GVAR_STEAL_NECKLACE_4 = 433,
    GVAR_STEAL_NECKLACE_5 = 434,
    GVAR_STEAL_NECKLACE_6 = 435,
    GVAR_STEAL_NECKLACE_7 = 436,
    GVAR_STEAL_NECKLACE_8 = 437,
    GVAR_STEAL_NECKLACE_9 = 438,
    GVAR_STEAL_NECKLACE_10 = 439,
    GVAR_KILL_JAIN_1 = 440,
    GVAR_KILL_JAIN_2 = 441,
    GVAR_KILL_JAIN_3 = 442,
    GVAR_KILL_JAIN_4 = 443,
    GVAR_KILL_JAIN_5 = 444,
    GVAR_KILL_JAIN_6 = 445,
    GVAR_KILL_JAIN_7 = 446,
    GVAR_KILL_JAIN_8 = 447,
    GVAR_KILL_JAIN_9 = 448,
    GVAR_KILL_JAIN_10 = 449,
    GVAR_KILL_MERCHANT_1 = 450,
    GVAR_KILL_MERCHANT_2 = 451,
    GVAR_KILL_MERCHANT_3 = 452,
    GVAR_KILL_MERCHANT_4 = 453,
    GVAR_KILL_MERCHANT_5 = 454,
    GVAR_KILL_MERCHANT_6 = 455,
    GVAR_KILL_MERCHANT_7 = 456,
    GVAR_KILL_MERCHANT_8 = 457,
    GVAR_KILL_MERCHANT_9 = 458,
    GVAR_KILL_MERCHANT_10 = 459,
    GVAR_DEATHCLAW_SEED_1 = 460,
    GVAR_DEATHCLAW_SEED_2 = 461,
    GVAR_DEATHCLAW_SEED_3 = 462,
    GVAR_DEATHCLAW_SEED_4 = 463,
    GVAR_DEATHCLAW_SEED_5 = 464,
    GVAR_DEATHCLAW_SEED_6 = 465,
    GVAR_DEATHCLAW_SEED_7 = 466,
    GVAR_DEATHCLAW_SEED_8 = 467,
    GVAR_DEATHCLAW_SEED_9 = 468,
    GVAR_FRY_DEAD = 469,
    GVAR_MISSING_CARAVAN_1 = 470,
    GVAR_MISSING_CARAVAN_2 = 471,
    GVAR_MISSING_CARAVAN_3 = 472,
    GVAR_MISSING_CARAVAN_4 = 473,
    GVAR_MISSING_CARAVAN_5 = 474,
    GVAR_MISSING_CARAVAN_6 = 475,
    GVAR_MISSING_CARAVAN_7 = 476,
    GVAR_MISSING_CARAVAN_8 = 477,
    GVAR_MISSING_CARAVAN_9 = 478,
    GVAR_MISSING_CARAVAN_10 = 479,
    GVAR_BECOME_INITIATE_1 = 480,
    GVAR_BECOME_INITIATE_2 = 481,
    GVAR_BECOME_INITIATE_3 = 482,
    GVAR_BECOME_INITIATE_4 = 483,
    GVAR_BECOME_INITIATE_5 = 484,
    GVAR_BECOME_INITIATE_6 = 485,
    GVAR_BECOME_INITIATE_7 = 486,
    GVAR_BECOME_INITIATE_8 = 487,
    GVAR_BECOME_INITIATE_9 = 488,
    GVAR_BECOME_INITIATE_10 = 489,
    GVAR_FIND_INITIATE_1 = 490,
    GVAR_FIND_INITIATE_2 = 491,
    GVAR_FIND_INITIATE_3 = 492,
    GVAR_FIND_INITIATE_4 = 493,
    GVAR_FIND_INITIATE_5 = 494,
    GVAR_FIND_INITIATE_6 = 495,
    GVAR_FIND_INITIATE_7 = 496,
    GVAR_FIND_INITIATE_8 = 497,
    GVAR_FIND_INITIATE_9 = 498,
    GVAR_FIND_INITIATE_10 = 499,
    GVAR_ROMEO_JULIET_1 = 500,
    GVAR_STOP_GANGS_1 = 501,
    GVAR_STOP_GANGS_2 = 502,
    GVAR_STOP_GANGS_3 = 503,
    GVAR_STOP_GANGS_4 = 504,
    GVAR_STOP_GANGS_5 = 505,
    GVAR_STOP_GANGS_6 = 506,
    GVAR_STOP_GANGS_7 = 507,
    GVAR_STOP_GANGS_8 = 508,
    GVAR_STOP_GANGS_9 = 509,
    GVAR_CATCH_SPY_1 = 510,
    GVAR_CATCH_SPY_2 = 511,
    GVAR_CATCH_SPY_3 = 512,
    GVAR_CATCH_SPY_4 = 513,
    GVAR_CATCH_SPY_5 = 514,
    GVAR_CATCH_SPY_6 = 515,
    GVAR_CATCH_SPY_7 = 516,
    GVAR_CATCH_SPY_8 = 517,
    GVAR_CATCH_SPY_9 = 518,
    GVAR_CATCH_SPY_10 = 519,
    GVAR_CATCH_SPY_11 = 520,
    GVAR_CATCH_SPY_12 = 521,
    GVAR_CATCH_SPY_13 = 522,
    GVAR_CATCH_SPY_14 = 523,
    GVAR_CATCH_SPY_15 = 524,
    GVAR_CATCH_SPY_16 = 525,
    GVAR_CATCH_SPY_17 = 526,
    GVAR_CATCH_SPY_18 = 527,
    GVAR_CATCH_SPY_19 = 528,
    GVAR_BECOME_BLADE_1 = 529,
    GVAR_BECOME_BLADE_2 = 530,
    GVAR_BECOME_BLADE_3 = 531,
    GVAR_BECOME_BLADE_4 = 532,
    GVAR_DELIVER_PACKAGE_1 = 533,
    GVAR_DELIVER_PACKAGE_2 = 534,
    GVAR_DELIVER_PACKAGE_3 = 535,
    GVAR_DELIVER_PACKAGE_4 = 536,
    GVAR_DELIVER_PACKAGE_5 = 537,
    GVAR_FIX_FARM_1 = 538,
    GVAR_FIX_FARM_2 = 539,
    GVAR_FIX_FARM_3 = 540,
    GVAR_FIX_FARM_4 = 541,
    GVAR_LOST_BROTHER_1 = 542,
    GVAR_LOST_BROTHER_2 = 543,
    GVAR_LOST_BROTHER_3 = 544,
    GVAR_LOST_BROTHER_4 = 545,
    GVAR_LOST_BROTHER_5 = 546,
    GVAR_POWER_GLOW_1 = 547,
    GVAR_DISARM_TRAPS_1 = 548,
    GVAR_DISARM_TRAPS_2 = 549,
    GVAR_DISARM_TRAPS_3 = 550,
    GVAR_MAX_MUTANTS = 551,
    GVAR_TIME_CHIP_GONE = 552,
    GVAR_SET_DEAD = 553,
    GVAR_MUTANTS_GONE = 554,
    GVAR_BUST_SKULZ = 555,
    GVAR_SHERRY_TURNS = 556,
    GVAR_TRISH_STATUS = 557,
    GVAR_MARK_V13_1 = 558,
    GVAR_MARK_V13_2 = 559,
    GVAR_MARK_V13_3 = 560,
    GVAR_MARK_V13_4 = 561,
    GVAR_MARK_V15_1 = 562,
    GVAR_MARK_V15_2 = 563,
    GVAR_MARK_V15_3 = 564,
    GVAR_MARK_V15_4 = 565,
    GVAR_MARK_SHADY_1 = 566,
    GVAR_MARK_SHADY_2 = 567,
    GVAR_MARK_SHADY_3 = 568,
    GVAR_MARK_JUNK_1 = 569,
    GVAR_MARK_JUNK_2 = 570,
    GVAR_MARK_JUNK_3 = 571,
    GVAR_MARK_RAIDERS_1 = 572,
    GVAR_MARK_NECROP_1 = 573,
    GVAR_MARK_NECROP_2 = 574,
    GVAR_MARK_NECROP_3 = 575,
    GVAR_MARK_HUB_1 = 576,
    GVAR_MARK_HUB_2 = 577,
    GVAR_MARK_HUB_3 = 578,
    GVAR_MARK_HUB_4 = 579,
    GVAR_MARK_HUB_5 = 580,
    GVAR_MARK_HUB_6 = 581,
    GVAR_MARK_BROTHER_1 = 582,
    GVAR_MARK_BROTHER_2 = 583,
    GVAR_MARK_BROTHER_3 = 584,
    GVAR_MARK_BROTHER_4 = 585,
    GVAR_MARK_BROTHER_5 = 586,
    GVAR_MARK_BASE_1 = 587,
    GVAR_MARK_BASE_2 = 588,
    GVAR_MARK_BASE_3 = 589,
    GVAR_MARK_BASE_4 = 590,
    GVAR_MARK_BASE_5 = 591,
    GVAR_MARK_GLOW_1 = 592,
    GVAR_MARK_GLOW_2 = 593,
    GVAR_MARK_LA_1 = 594,
    GVAR_MARK_LA_2 = 595,
    GVAR_MARK_LA_3 = 596,
    GVAR_MARK_LA_4 = 597,
    GVAR_MARK_LA_5 = 598,
    GVAR_MARK_CHILD_1 = 599,
    GVAR_MARK_CHILD_2 = 600,
    GVAR_STRANGER_STATUS = 601,
    GVAR_GAME_DIFFICULTY = 602,
    GVAR_RUNNING_BURNING_GUY = 603,
    GVAR_ARADESH_STATUS = 604,
    GVAR_RHOMBUS_STATUS = 605,
    GVAR_KIND_TO_HAROLD = 606,
    GVAR_GARRET_STATUS = 607,
    GVAR_RADIO_COMPUTER_OFF = 608,
    GVAR_FORCE_FIELDS_OFF = 609,
    GVAR_FIELD_COMPUTER_MODIFIED = 610,
    GVAR_GARLS_FRIEND = 611,
    GVAR_ZIMMERMAN = 612,
    GVAR_BLADES = 613,
    GVAR_GUN_RUNNER = 614,
    GVAR_CHEMISTRY_BOOK = 615,
    GVAR_ENEMY_REGULATOR = 616,
    GVAR_ENEMY_BLADE = 617,
};

inline constexpr int GVAR_CHILD_KILLER_SHADY = static_cast<int>(GameGlobalVar::GVAR_CHILD_KILLER_SHADY);
inline constexpr int GVAR_CHILD_KILLER_HUB = static_cast<int>(GameGlobalVar::GVAR_CHILD_KILLER_HUB);
inline constexpr int GVAR_NUM_RADSCORPIONS = static_cast<int>(GameGlobalVar::GVAR_NUM_RADSCORPIONS);
inline constexpr int GVAR_CHILD_KILLER_ADYTUM = static_cast<int>(GameGlobalVar::GVAR_CHILD_KILLER_ADYTUM);
inline constexpr int GVAR_DOGS_KILLED = static_cast<int>(GameGlobalVar::GVAR_DOGS_KILLED);
inline constexpr int GVAR_DOG_EMPATHY = static_cast<int>(GameGlobalVar::GVAR_DOG_EMPATHY);
inline constexpr int GVAR_QUEST_PEOPLE = static_cast<int>(GameGlobalVar::GVAR_QUEST_PEOPLE);
inline constexpr int GVAR_FOLLOWERS_INVADED = static_cast<int>(GameGlobalVar::GVAR_FOLLOWERS_INVADED);
inline constexpr int GVAR_MAP_ENTRANCE_NUMBER = static_cast<int>(GameGlobalVar::GVAR_MAP_ENTRANCE_NUMBER);
inline constexpr int GVAR_DAYS_TO_VAULT13_DISCOVERY = static_cast<int>(GameGlobalVar::GVAR_DAYS_TO_VAULT13_DISCOVERY);
inline constexpr int GVAR_VAULT_WATER = static_cast<int>(GameGlobalVar::GVAR_VAULT_WATER);
inline constexpr int GVAR_VAULT_INVADED = static_cast<int>(GameGlobalVar::GVAR_VAULT_INVADED);
inline constexpr int GVAR_SHADY_SANDS_INVADED = static_cast<int>(GameGlobalVar::GVAR_SHADY_SANDS_INVADED);
inline constexpr int GVAR_NECROPOLIS_INVADED = static_cast<int>(GameGlobalVar::GVAR_NECROPOLIS_INVADED);
inline constexpr int GVAR_HUB_INVADED = static_cast<int>(GameGlobalVar::GVAR_HUB_INVADED);
inline constexpr int GVAR_JUNKTOWN_INVADED = static_cast<int>(GameGlobalVar::GVAR_JUNKTOWN_INVADED);
inline constexpr int GVAR_BROTHERHOOD_INVADED = static_cast<int>(GameGlobalVar::GVAR_BROTHERHOOD_INVADED);
inline constexpr int GVAR_VATS_BLOWN = static_cast<int>(GameGlobalVar::GVAR_VATS_BLOWN);
inline constexpr int GVAR_MASTER_BLOWN = static_cast<int>(GameGlobalVar::GVAR_MASTER_BLOWN);
inline constexpr int GVAR_NECROPOLIS_VISITED = static_cast<int>(GameGlobalVar::GVAR_NECROPOLIS_VISITED);
inline constexpr int GVAR_NECROPOLIS_KNOWN = static_cast<int>(GameGlobalVar::GVAR_NECROPOLIS_KNOWN);
inline constexpr int GVAR_MOTEL_OF_DOOM_VISITED = static_cast<int>(GameGlobalVar::GVAR_MOTEL_OF_DOOM_VISITED);
inline constexpr int GVAR_HALL_OF_THE_DEAD_VISITED = static_cast<int>(GameGlobalVar::GVAR_HALL_OF_THE_DEAD_VISITED);
inline constexpr int GVAR_WATERSHED_VISITED = static_cast<int>(GameGlobalVar::GVAR_WATERSHED_VISITED);
inline constexpr int GVAR_NECROPOLIS_VAULT_VISITED = static_cast<int>(GameGlobalVar::GVAR_NECROPOLIS_VAULT_VISITED);
inline constexpr int GVAR_TANDI_X = static_cast<int>(GameGlobalVar::GVAR_TANDI_X);
inline constexpr int GVAR_TANDI_STATUS = static_cast<int>(GameGlobalVar::GVAR_TANDI_STATUS);
inline constexpr int GVAR_TANDI_DEAD = static_cast<int>(GameGlobalVar::GVAR_TANDI_DEAD);
inline constexpr int GVAR_RADSCORPIONS_KILLED = static_cast<int>(GameGlobalVar::GVAR_RADSCORPIONS_KILLED);
inline constexpr int GVAR_NECROP_MUTANTS_KILLED = static_cast<int>(GameGlobalVar::GVAR_NECROP_MUTANTS_KILLED);
inline constexpr int GVAR_NECROP_WATER_CHIP_TAKEN = static_cast<int>(GameGlobalVar::GVAR_NECROP_WATER_CHIP_TAKEN);
inline constexpr int GVAR_NECROP_WATER_PUMP_FIXED = static_cast<int>(GameGlobalVar::GVAR_NECROP_WATER_PUMP_FIXED);
inline constexpr int GVAR_LOAD_MAP_INDEX = static_cast<int>(GameGlobalVar::GVAR_LOAD_MAP_INDEX);
inline constexpr int GVAR_ANIMALS_KILLED = static_cast<int>(GameGlobalVar::GVAR_ANIMALS_KILLED);
inline constexpr int GVAR_HUMANS_KILLED = static_cast<int>(GameGlobalVar::GVAR_HUMANS_KILLED);
inline constexpr int GVAR_SUPER_MUTANTS_KILLED = static_cast<int>(GameGlobalVar::GVAR_SUPER_MUTANTS_KILLED);
inline constexpr int GVAR_HIRED_BY_KILLIAN = static_cast<int>(GameGlobalVar::GVAR_HIRED_BY_KILLIAN);
inline constexpr int GVAR_KILLIAN_DEAD = static_cast<int>(GameGlobalVar::GVAR_KILLIAN_DEAD);
inline constexpr int GVAR_GIZMO_DEAD = static_cast<int>(GameGlobalVar::GVAR_GIZMO_DEAD);
inline constexpr int GVAR_HIRED_BY_GIZMO = static_cast<int>(GameGlobalVar::GVAR_HIRED_BY_GIZMO);
inline constexpr int GVAR_IN_JAIL = static_cast<int>(GameGlobalVar::GVAR_IN_JAIL);
inline constexpr int GVAR_BUG_PLANTED = static_cast<int>(GameGlobalVar::GVAR_BUG_PLANTED);
inline constexpr int GVAR_GOT_CONFESSION = static_cast<int>(GameGlobalVar::GVAR_GOT_CONFESSION);
inline constexpr int GVAR_RADSCORPION_SEED = static_cast<int>(GameGlobalVar::GVAR_RADSCORPION_SEED);
inline constexpr int GVAR_DEATHCLAW_SEED = static_cast<int>(GameGlobalVar::GVAR_DEATHCLAW_SEED);
inline constexpr int GVAR_BROTHERHOOD_SEED = static_cast<int>(GameGlobalVar::GVAR_BROTHERHOOD_SEED);
inline constexpr int GVAR_HUB_SEED = static_cast<int>(GameGlobalVar::GVAR_HUB_SEED);
inline constexpr int GVAR_PLAYER_LOCATION = static_cast<int>(GameGlobalVar::GVAR_PLAYER_LOCATION);
inline constexpr int GVAR_LOXLEY_X = static_cast<int>(GameGlobalVar::GVAR_LOXLEY_X);
inline constexpr int GVAR_MAXSON_X = static_cast<int>(GameGlobalVar::GVAR_MAXSON_X);
inline constexpr int GVAR_CATHEDRAL = static_cast<int>(GameGlobalVar::GVAR_CATHEDRAL);
inline constexpr int GVAR_VATS_STATUS = static_cast<int>(GameGlobalVar::GVAR_VATS_STATUS);
inline constexpr int GVAR_CHILDREN_STATUS = static_cast<int>(GameGlobalVar::GVAR_CHILDREN_STATUS);
inline constexpr int GVAR_MASTER_DEAD = static_cast<int>(GameGlobalVar::GVAR_MASTER_DEAD);
inline constexpr int GVAR_LIEUTENANTS_DEAD = static_cast<int>(GameGlobalVar::GVAR_LIEUTENANTS_DEAD);
inline constexpr int GVAR_COUNTDOWN_TO_DESTRUCTION = static_cast<int>(GameGlobalVar::GVAR_COUNTDOWN_TO_DESTRUCTION);
inline constexpr int GVAR_BOMB_DISARMED = static_cast<int>(GameGlobalVar::GVAR_BOMB_DISARMED);
inline constexpr int GVAR_ENTERING_VATS_HOW = static_cast<int>(GameGlobalVar::GVAR_ENTERING_VATS_HOW);
inline constexpr int GVAR_WATER_SHED_STATUS = static_cast<int>(GameGlobalVar::GVAR_WATER_SHED_STATUS);
inline constexpr int GVAR_PLAYER_CAPTURED = static_cast<int>(GameGlobalVar::GVAR_PLAYER_CAPTURED);
inline constexpr int GVAR_SIGNAL_REWARD = static_cast<int>(GameGlobalVar::GVAR_SIGNAL_REWARD);
inline constexpr int GVAR_SHADOW_PASSWORD = static_cast<int>(GameGlobalVar::GVAR_SHADOW_PASSWORD);
inline constexpr int GVAR_FOLLOWER_STEALTH_HELP = static_cast<int>(GameGlobalVar::GVAR_FOLLOWER_STEALTH_HELP);
inline constexpr int GVAR_FOLLOWER_MACHO_HELP = static_cast<int>(GameGlobalVar::GVAR_FOLLOWER_MACHO_HELP);
inline constexpr int GVAR_KNIGHT_WARNING = static_cast<int>(GameGlobalVar::GVAR_KNIGHT_WARNING);
inline constexpr int GVAR_WORLD_TERRAIN = static_cast<int>(GameGlobalVar::GVAR_WORLD_TERRAIN);
inline constexpr int GVAR_NECROP_WATER = static_cast<int>(GameGlobalVar::GVAR_NECROP_WATER);
inline constexpr int GVAR_VAULT_13 = static_cast<int>(GameGlobalVar::GVAR_VAULT_13);
inline constexpr int GVAR_SHADY_SANDS = static_cast<int>(GameGlobalVar::GVAR_SHADY_SANDS);
inline constexpr int GVAR_RAIDERS = static_cast<int>(GameGlobalVar::GVAR_RAIDERS);
inline constexpr int GVAR_BURIED_VAULT = static_cast<int>(GameGlobalVar::GVAR_BURIED_VAULT);
inline constexpr int GVAR_JUNKTOWN = static_cast<int>(GameGlobalVar::GVAR_JUNKTOWN);
inline constexpr int GVAR_NECROPOLIS = static_cast<int>(GameGlobalVar::GVAR_NECROPOLIS);
inline constexpr int GVAR_THE_HUB = static_cast<int>(GameGlobalVar::GVAR_THE_HUB);
inline constexpr int GVAR_BROTHERHOOD_OF_STEEL = static_cast<int>(GameGlobalVar::GVAR_BROTHERHOOD_OF_STEEL);
inline constexpr int GVAR_ANGELS_BONEYARD = static_cast<int>(GameGlobalVar::GVAR_ANGELS_BONEYARD);
inline constexpr int GVAR_THE_GLOW = static_cast<int>(GameGlobalVar::GVAR_THE_GLOW);
inline constexpr int GVAR_CHILDREN_OF_CATHEDRAL = static_cast<int>(GameGlobalVar::GVAR_CHILDREN_OF_CATHEDRAL);
inline constexpr int GVAR_THE_VATS = static_cast<int>(GameGlobalVar::GVAR_THE_VATS);
inline constexpr int GVAR_MASTERS_LAIR = static_cast<int>(GameGlobalVar::GVAR_MASTERS_LAIR);
inline constexpr int GVAR_BROTHERHOOD_12 = static_cast<int>(GameGlobalVar::GVAR_BROTHERHOOD_12);
inline constexpr int GVAR_BROTHERHOOD_34 = static_cast<int>(GameGlobalVar::GVAR_BROTHERHOOD_34);
inline constexpr int GVAR_BROTHERHOOD_ENTRANCE = static_cast<int>(GameGlobalVar::GVAR_BROTHERHOOD_ENTRANCE);
inline constexpr int GVAR_CAVES = static_cast<int>(GameGlobalVar::GVAR_CAVES);
inline constexpr int GVAR_CHILDREN_1 = static_cast<int>(GameGlobalVar::GVAR_CHILDREN_1);
inline constexpr int GVAR_DESERT_1 = static_cast<int>(GameGlobalVar::GVAR_DESERT_1);
inline constexpr int GVAR_DESERT_2 = static_cast<int>(GameGlobalVar::GVAR_DESERT_2);
inline constexpr int GVAR_DESERT_3 = static_cast<int>(GameGlobalVar::GVAR_DESERT_3);
inline constexpr int GVAR_HALL_OF_THE_DEAD = static_cast<int>(GameGlobalVar::GVAR_HALL_OF_THE_DEAD);
inline constexpr int GVAR_HOTEL_OF_DOOM = static_cast<int>(GameGlobalVar::GVAR_HOTEL_OF_DOOM);
inline constexpr int GVAR_JUNKTOWN_CASINO = static_cast<int>(GameGlobalVar::GVAR_JUNKTOWN_CASINO);
inline constexpr int GVAR_JUNKTOWN_ENTRANCE = static_cast<int>(GameGlobalVar::GVAR_JUNKTOWN_ENTRANCE);
inline constexpr int GVAR_JUNKTOWN_KILLIAN = static_cast<int>(GameGlobalVar::GVAR_JUNKTOWN_KILLIAN);
inline constexpr int GVAR_SHADY_SANDS_EAST = static_cast<int>(GameGlobalVar::GVAR_SHADY_SANDS_EAST);
inline constexpr int GVAR_SHADY_SANDS_WEST = static_cast<int>(GameGlobalVar::GVAR_SHADY_SANDS_WEST);
inline constexpr int GVAR_VAULT_13_MAP = static_cast<int>(GameGlobalVar::GVAR_VAULT_13_MAP);
inline constexpr int GVAR_BURIED_VAULT_MAP = static_cast<int>(GameGlobalVar::GVAR_BURIED_VAULT_MAP);
inline constexpr int GVAR_VAULT_ENTRANCE = static_cast<int>(GameGlobalVar::GVAR_VAULT_ENTRANCE);
inline constexpr int GVAR_NECROP_VAULT = static_cast<int>(GameGlobalVar::GVAR_NECROP_VAULT);
inline constexpr int GVAR_WATERSHED = static_cast<int>(GameGlobalVar::GVAR_WATERSHED);
inline constexpr int GVAR_KILL_DEATHCLAW = static_cast<int>(GameGlobalVar::GVAR_KILL_DEATHCLAW);
inline constexpr int GVAR_FIND_WATER_CHIP = static_cast<int>(GameGlobalVar::GVAR_FIND_WATER_CHIP);
inline constexpr int GVAR_KILL_RADSCORPIONS = static_cast<int>(GameGlobalVar::GVAR_KILL_RADSCORPIONS);
inline constexpr int GVAR_RESCUE_TANDI = static_cast<int>(GameGlobalVar::GVAR_RESCUE_TANDI);
inline constexpr int GVAR_CAPTURE_GIZMO = static_cast<int>(GameGlobalVar::GVAR_CAPTURE_GIZMO);
inline constexpr int GVAR_KILL_KILLIAN = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN);
inline constexpr int GVAR_MISSING_CARAVAN = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN);
inline constexpr int GVAR_STEAL_NECKLACE = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE);
inline constexpr int GVAR_BECOME_AN_INITIATE = static_cast<int>(GameGlobalVar::GVAR_BECOME_AN_INITIATE);
inline constexpr int GVAR_FIND_LOST_INITIATE = static_cast<int>(GameGlobalVar::GVAR_FIND_LOST_INITIATE);
inline constexpr int GVAR_WARNED_BROTHERHOOD = static_cast<int>(GameGlobalVar::GVAR_WARNED_BROTHERHOOD);
inline constexpr int GVAR_KILL_MERCHANT = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT);
inline constexpr int GVAR_KILL_JAIN = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN);
inline constexpr int GVAR_KILL_SUPER_MUTANTS = static_cast<int>(GameGlobalVar::GVAR_KILL_SUPER_MUTANTS);
inline constexpr int GVAR_GARL_DEAD = static_cast<int>(GameGlobalVar::GVAR_GARL_DEAD);
inline constexpr int GVAR_TOTAL_RAIDERS = static_cast<int>(GameGlobalVar::GVAR_TOTAL_RAIDERS);
inline constexpr int GVAR_MISTAKEN_ID = static_cast<int>(GameGlobalVar::GVAR_MISTAKEN_ID);
inline constexpr int GVAR_WITH_CARAVAN = static_cast<int>(GameGlobalVar::GVAR_WITH_CARAVAN);
inline constexpr int GVAR_IAN_STATUS = static_cast<int>(GameGlobalVar::GVAR_IAN_STATUS);
inline constexpr int GVAR_TOLYA_STATUS = static_cast<int>(GameGlobalVar::GVAR_TOLYA_STATUS);
inline constexpr int GVAR_PETROX_STATUS = static_cast<int>(GameGlobalVar::GVAR_PETROX_STATUS);
inline constexpr int GVAR_HERNANDEZ_STATUS = static_cast<int>(GameGlobalVar::GVAR_HERNANDEZ_STATUS);
inline constexpr int GVAR_KENJI_STATUS = static_cast<int>(GameGlobalVar::GVAR_KENJI_STATUS);
inline constexpr int GVAR_HUNTER_STATUS = static_cast<int>(GameGlobalVar::GVAR_HUNTER_STATUS);
inline constexpr int GVAR_SETH_STATUS = static_cast<int>(GameGlobalVar::GVAR_SETH_STATUS);
inline constexpr int GVAR_TRENT_STATUS = static_cast<int>(GameGlobalVar::GVAR_TRENT_STATUS);
inline constexpr int GVAR_JASON_STATUS = static_cast<int>(GameGlobalVar::GVAR_JASON_STATUS);
inline constexpr int GVAR_ROMEO_JULIET = static_cast<int>(GameGlobalVar::GVAR_ROMEO_JULIET);
inline constexpr int GVAR_GANG_WAR = static_cast<int>(GameGlobalVar::GVAR_GANG_WAR);
inline constexpr int GVAR_DESTROY_FOLLOWERS = static_cast<int>(GameGlobalVar::GVAR_DESTROY_FOLLOWERS);
inline constexpr int GVAR_LOST_BROTHER = static_cast<int>(GameGlobalVar::GVAR_LOST_BROTHER);
inline constexpr int GVAR_BLADES_HELP = static_cast<int>(GameGlobalVar::GVAR_BLADES_HELP);
inline constexpr int GVAR_TRAIN_FOLLOWERS = static_cast<int>(GameGlobalVar::GVAR_TRAIN_FOLLOWERS);
inline constexpr int GVAR_FIND_AGENT = static_cast<int>(GameGlobalVar::GVAR_FIND_AGENT);
inline constexpr int GVAR_TANGLER_DEAD = static_cast<int>(GameGlobalVar::GVAR_TANGLER_DEAD);
inline constexpr int GVAR_BECOME_BLADE = static_cast<int>(GameGlobalVar::GVAR_BECOME_BLADE);
inline constexpr int GVAR_BLADES_LEFT = static_cast<int>(GameGlobalVar::GVAR_BLADES_LEFT);
inline constexpr int GVAR_RIPPERS_LEFT = static_cast<int>(GameGlobalVar::GVAR_RIPPERS_LEFT);
inline constexpr int GVAR_FIX_FARM = static_cast<int>(GameGlobalVar::GVAR_FIX_FARM);
inline constexpr int GVAR_START_POWER = static_cast<int>(GameGlobalVar::GVAR_START_POWER);
inline constexpr int GVAR_WEAPONS_ARMED = static_cast<int>(GameGlobalVar::GVAR_WEAPONS_ARMED);
inline constexpr int GVAR_FOUND_DISK = static_cast<int>(GameGlobalVar::GVAR_FOUND_DISK);
inline constexpr int GVAR_WEAPON_LOCKER = static_cast<int>(GameGlobalVar::GVAR_WEAPON_LOCKER);
inline constexpr int GVAR_SAVE_SINTHIA = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA);
inline constexpr int GVAR_SAUL_QUEST = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST);
inline constexpr int GVAR_TRISH_QUEST = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST);
inline constexpr int GVAR_VATS_ALERT = static_cast<int>(GameGlobalVar::GVAR_VATS_ALERT);
inline constexpr int GVAR_VATS_COUNTDOWN = static_cast<int>(GameGlobalVar::GVAR_VATS_COUNTDOWN);
inline constexpr int GVAR_FOLLOWERS_INVADED_DATE = static_cast<int>(GameGlobalVar::GVAR_FOLLOWERS_INVADED_DATE);
inline constexpr int GVAR_NECROPOLIS_INVADED_DATE = static_cast<int>(GameGlobalVar::GVAR_NECROPOLIS_INVADED_DATE);
inline constexpr int GVAR_THE_HUB_INVADED_DATE = static_cast<int>(GameGlobalVar::GVAR_THE_HUB_INVADED_DATE);
inline constexpr int GVAR_BROTHERHOOD_INVADED_DATE = static_cast<int>(GameGlobalVar::GVAR_BROTHERHOOD_INVADED_DATE);
inline constexpr int GVAR_JUNKTOWN_INVADED_DATE = static_cast<int>(GameGlobalVar::GVAR_JUNKTOWN_INVADED_DATE);
inline constexpr int GVAR_SHADY_SANDS_INVADED_DATE = static_cast<int>(GameGlobalVar::GVAR_SHADY_SANDS_INVADED_DATE);
inline constexpr int GVAR_VAULT_13_INVADED_DATE = static_cast<int>(GameGlobalVar::GVAR_VAULT_13_INVADED_DATE);
inline constexpr int GVAR_PLAYER_REPUATION = static_cast<int>(GameGlobalVar::GVAR_PLAYER_REPUATION);
inline constexpr int GVAR_BERSERKER_REPUTATION = static_cast<int>(GameGlobalVar::GVAR_BERSERKER_REPUTATION);
inline constexpr int GVAR_CHAMPION_REPUTATION = static_cast<int>(GameGlobalVar::GVAR_CHAMPION_REPUTATION);
inline constexpr int GVAR_CHILDKILLER_REPUATION = static_cast<int>(GameGlobalVar::GVAR_CHILDKILLER_REPUATION);
inline constexpr int GVAR_GOOD_MONSTER = static_cast<int>(GameGlobalVar::GVAR_GOOD_MONSTER);
inline constexpr int GVAR_BAD_MONSTER = static_cast<int>(GameGlobalVar::GVAR_BAD_MONSTER);
inline constexpr int GVAR_ARTIFACT_DISK = static_cast<int>(GameGlobalVar::GVAR_ARTIFACT_DISK);
inline constexpr int GVAR_FEV_DISK = static_cast<int>(GameGlobalVar::GVAR_FEV_DISK);
inline constexpr int GVAR_SECURITY_DISK = static_cast<int>(GameGlobalVar::GVAR_SECURITY_DISK);
inline constexpr int GVAR_ALPHA_DISK = static_cast<int>(GameGlobalVar::GVAR_ALPHA_DISK);
inline constexpr int GVAR_DELTA_DISK = static_cast<int>(GameGlobalVar::GVAR_DELTA_DISK);
inline constexpr int GVAR_VREE_DISK = static_cast<int>(GameGlobalVar::GVAR_VREE_DISK);
inline constexpr int GVAR_HONOR_DISK = static_cast<int>(GameGlobalVar::GVAR_HONOR_DISK);
inline constexpr int GVAR_RENT_TIME = static_cast<int>(GameGlobalVar::GVAR_RENT_TIME);
inline constexpr int GVAR_SAUL_STATUS = static_cast<int>(GameGlobalVar::GVAR_SAUL_STATUS);
inline constexpr int GVAR_GIZMO_STATUS = static_cast<int>(GameGlobalVar::GVAR_GIZMO_STATUS);
inline constexpr int GVAR_GANGS = static_cast<int>(GameGlobalVar::GVAR_GANGS);
inline constexpr int GVAR_GANG_BEGONE = static_cast<int>(GameGlobalVar::GVAR_GANG_BEGONE);
inline constexpr int GVAR_GANG_1 = static_cast<int>(GameGlobalVar::GVAR_GANG_1);
inline constexpr int GVAR_GANG_2 = static_cast<int>(GameGlobalVar::GVAR_GANG_2);
inline constexpr int GVAR_FOOLS_SCOUT = static_cast<int>(GameGlobalVar::GVAR_FOOLS_SCOUT);
inline constexpr int GVAR_FSCOUT_1 = static_cast<int>(GameGlobalVar::GVAR_FSCOUT_1);
inline constexpr int GVAR_CRYPTS_SCOUT = static_cast<int>(GameGlobalVar::GVAR_CRYPTS_SCOUT);
inline constexpr int GVAR_CSCOUT_1 = static_cast<int>(GameGlobalVar::GVAR_CSCOUT_1);
inline constexpr int GVAR_POWER = static_cast<int>(GameGlobalVar::GVAR_POWER);
inline constexpr int GVAR_POWER_GENERATOR = static_cast<int>(GameGlobalVar::GVAR_POWER_GENERATOR);
inline constexpr int GVAR_GENERATOR_1 = static_cast<int>(GameGlobalVar::GVAR_GENERATOR_1);
inline constexpr int GVAR_GENERATOR_2 = static_cast<int>(GameGlobalVar::GVAR_GENERATOR_2);
inline constexpr int GVAR_GENERATOR_3 = static_cast<int>(GameGlobalVar::GVAR_GENERATOR_3);
inline constexpr int GVAR_PEASANTS = static_cast<int>(GameGlobalVar::GVAR_PEASANTS);
inline constexpr int GVAR_DOG_PHIL = static_cast<int>(GameGlobalVar::GVAR_DOG_PHIL);
inline constexpr int GVAR_DOG_1 = static_cast<int>(GameGlobalVar::GVAR_DOG_1);
inline constexpr int GVAR_DOG_2 = static_cast<int>(GameGlobalVar::GVAR_DOG_2);
inline constexpr int GVAR_WATER_THIEF = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF);
inline constexpr int GVAR_NUKA_COLA_ADDICT = static_cast<int>(GameGlobalVar::GVAR_NUKA_COLA_ADDICT);
inline constexpr int GVAR_BUFF_OUT_ADDICT = static_cast<int>(GameGlobalVar::GVAR_BUFF_OUT_ADDICT);
inline constexpr int GVAR_MENTATS_ADDICT = static_cast<int>(GameGlobalVar::GVAR_MENTATS_ADDICT);
inline constexpr int GVAR_PSYCHO_ADDICT = static_cast<int>(GameGlobalVar::GVAR_PSYCHO_ADDICT);
inline constexpr int GVAR_RADAWAY_ADDICT = static_cast<int>(GameGlobalVar::GVAR_RADAWAY_ADDICT);
inline constexpr int GVAR_ALCOHOL_ADDICT = static_cast<int>(GameGlobalVar::GVAR_ALCOHOL_ADDICT);
inline constexpr int GVAR_CATHEDRAL_ENEMY = static_cast<int>(GameGlobalVar::GVAR_CATHEDRAL_ENEMY);
inline constexpr int GVAR_MORPHEUS_KNOWN = static_cast<int>(GameGlobalVar::GVAR_MORPHEUS_KNOWN);
inline constexpr int GVAR_KNOW_NIGHTKIN = static_cast<int>(GameGlobalVar::GVAR_KNOW_NIGHTKIN);
inline constexpr int GVAR_PC_WANTED = static_cast<int>(GameGlobalVar::GVAR_PC_WANTED);
inline constexpr int GVAR_CRIMSON_CARAVANS_STATUS = static_cast<int>(GameGlobalVar::GVAR_CRIMSON_CARAVANS_STATUS);
inline constexpr int GVAR_WATER_MERCHANTS_STATUS = static_cast<int>(GameGlobalVar::GVAR_WATER_MERCHANTS_STATUS);
inline constexpr int GVAR_FARGO_TRADERS_STATUS = static_cast<int>(GameGlobalVar::GVAR_FARGO_TRADERS_STATUS);
inline constexpr int GVAR_UNDERGROUND_STATUS = static_cast<int>(GameGlobalVar::GVAR_UNDERGROUND_STATUS);
inline constexpr int GVAR_DECKER_STATUS = static_cast<int>(GameGlobalVar::GVAR_DECKER_STATUS);
inline constexpr int GVAR_CC_JOB = static_cast<int>(GameGlobalVar::GVAR_CC_JOB);
inline constexpr int GVAR_WATER_JOB = static_cast<int>(GameGlobalVar::GVAR_WATER_JOB);
inline constexpr int GVAR_FARGO_JOB = static_cast<int>(GameGlobalVar::GVAR_FARGO_JOB);
inline constexpr int GVAR_Loxley_known = static_cast<int>(GameGlobalVar::GVAR_Loxley_known);
inline constexpr int GVAR_MARK_DEATHCLAW = static_cast<int>(GameGlobalVar::GVAR_MARK_DEATHCLAW);
inline constexpr int GVAR_MUTANT_DISK = static_cast<int>(GameGlobalVar::GVAR_MUTANT_DISK);
inline constexpr int GVAR_BROTHER_HISTORY = static_cast<int>(GameGlobalVar::GVAR_BROTHER_HISTORY);
inline constexpr int GVAR_SOPHIA_DISK = static_cast<int>(GameGlobalVar::GVAR_SOPHIA_DISK);
inline constexpr int GVAR_MAXSON_DISK = static_cast<int>(GameGlobalVar::GVAR_MAXSON_DISK);
inline constexpr int GVAR_TANDI_ESCAPE = static_cast<int>(GameGlobalVar::GVAR_TANDI_ESCAPE);
inline constexpr int GVAR_RAID_LOOTING = static_cast<int>(GameGlobalVar::GVAR_RAID_LOOTING);
inline constexpr int GVAR_CVAN_DRIVER = static_cast<int>(GameGlobalVar::GVAR_CVAN_DRIVER);
inline constexpr int GVAR_CVAN_GUARD = static_cast<int>(GameGlobalVar::GVAR_CVAN_GUARD);
inline constexpr int GVAR_TANDI_HEREBEFORE = static_cast<int>(GameGlobalVar::GVAR_TANDI_HEREBEFORE);
inline constexpr int GVAR_TALKED_ABOUT_TANDI = static_cast<int>(GameGlobalVar::GVAR_TALKED_ABOUT_TANDI);
inline constexpr int GVAR_DECKER_KNOWN = static_cast<int>(GameGlobalVar::GVAR_DECKER_KNOWN);
inline constexpr int GVAR_WANTED_FOR_MURDER = static_cast<int>(GameGlobalVar::GVAR_WANTED_FOR_MURDER);
inline constexpr int GVAR_GREENE_DEAD = static_cast<int>(GameGlobalVar::GVAR_GREENE_DEAD);
inline constexpr int GVAR_WANTED_THEFT = static_cast<int>(GameGlobalVar::GVAR_WANTED_THEFT);
inline constexpr int GVAR_BROTHERHOOD_INVASION = static_cast<int>(GameGlobalVar::GVAR_BROTHERHOOD_INVASION);
inline constexpr int GVAR_GLOW_POWER = static_cast<int>(GameGlobalVar::GVAR_GLOW_POWER);
inline constexpr int GVAR_HUB_FILLER_28 = static_cast<int>(GameGlobalVar::GVAR_HUB_FILLER_28);
inline constexpr int GVAR_HUB_FILLER_29 = static_cast<int>(GameGlobalVar::GVAR_HUB_FILLER_29);
inline constexpr int GVAR_HUB_FILLER_30 = static_cast<int>(GameGlobalVar::GVAR_HUB_FILLER_30);
inline constexpr int GVAR_NUM_RADIO = static_cast<int>(GameGlobalVar::GVAR_NUM_RADIO);
inline constexpr int GVAR_RADIO_MISTAKE = static_cast<int>(GameGlobalVar::GVAR_RADIO_MISTAKE);
inline constexpr int GVAR_CHANNEL_SLOT_DOWN = static_cast<int>(GameGlobalVar::GVAR_CHANNEL_SLOT_DOWN);
inline constexpr int GVAR_MASTER_FILLER_4 = static_cast<int>(GameGlobalVar::GVAR_MASTER_FILLER_4);
inline constexpr int GVAR_MASTER_FILLER_5 = static_cast<int>(GameGlobalVar::GVAR_MASTER_FILLER_5);
inline constexpr int GVAR_MASTER_FILLER_6 = static_cast<int>(GameGlobalVar::GVAR_MASTER_FILLER_6);
inline constexpr int GVAR_MASTER_FILLER_7 = static_cast<int>(GameGlobalVar::GVAR_MASTER_FILLER_7);
inline constexpr int GVAR_MASTER_FILLER_8 = static_cast<int>(GameGlobalVar::GVAR_MASTER_FILLER_8);
inline constexpr int GVAR_MASTER_FILLER_9 = static_cast<int>(GameGlobalVar::GVAR_MASTER_FILLER_9);
inline constexpr int GVAR_MASTER_FILLER_10 = static_cast<int>(GameGlobalVar::GVAR_MASTER_FILLER_10);
inline constexpr int GVAR_CALM_REBELS = static_cast<int>(GameGlobalVar::GVAR_CALM_REBELS);
inline constexpr int GVAR_CURE_JARVIS = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS);
inline constexpr int GVAR_MAKE_ANTIDOTE = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE);
inline constexpr int GVAR_MORPHEUS_DELIVERS_PLAYER = static_cast<int>(GameGlobalVar::GVAR_MORPHEUS_DELIVERS_PLAYER);
inline constexpr int GVAR_DESTROY_VATS = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS);
inline constexpr int GVAR_DESTROY_MASTER = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER);
inline constexpr int GVAR_KATJA_STATUS = static_cast<int>(GameGlobalVar::GVAR_KATJA_STATUS);
inline constexpr int GVAR_ENEMY_VAULT_13 = static_cast<int>(GameGlobalVar::GVAR_ENEMY_VAULT_13);
inline constexpr int GVAR_ENEMY_SHADY_SANDS = static_cast<int>(GameGlobalVar::GVAR_ENEMY_SHADY_SANDS);
inline constexpr int GVAR_ENEMY_JUNKTOWN = static_cast<int>(GameGlobalVar::GVAR_ENEMY_JUNKTOWN);
inline constexpr int GVAR_ENEMY_HUB = static_cast<int>(GameGlobalVar::GVAR_ENEMY_HUB);
inline constexpr int GVAR_ENEMY_NECROPOLIS = static_cast<int>(GameGlobalVar::GVAR_ENEMY_NECROPOLIS);
inline constexpr int GVAR_ENEMY_BROTHERHOOD = static_cast<int>(GameGlobalVar::GVAR_ENEMY_BROTHERHOOD);
inline constexpr int GVAR_ENEMY_ADYTUM = static_cast<int>(GameGlobalVar::GVAR_ENEMY_ADYTUM);
inline constexpr int GVAR_ENEMY_RIPPERS = static_cast<int>(GameGlobalVar::GVAR_ENEMY_RIPPERS);
inline constexpr int GVAR_ENEMY_BLADES = static_cast<int>(GameGlobalVar::GVAR_ENEMY_BLADES);
inline constexpr int GVAR_ENEMY_RAIDERS = static_cast<int>(GameGlobalVar::GVAR_ENEMY_RAIDERS);
inline constexpr int GVAR_ENEMY_CATHEDRAL = static_cast<int>(GameGlobalVar::GVAR_ENEMY_CATHEDRAL);
inline constexpr int GVAR_ENEMY_FOLLOWERS = static_cast<int>(GameGlobalVar::GVAR_ENEMY_FOLLOWERS);
inline constexpr int GVAR_GENERIC_FILLER_20 = static_cast<int>(GameGlobalVar::GVAR_GENERIC_FILLER_20);
inline constexpr int GVAR_WATER_CHIP_1 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_1);
inline constexpr int GVAR_WATER_CHIP_2 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_2);
inline constexpr int GVAR_WATER_CHIP_3 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_3);
inline constexpr int GVAR_WATER_CHIP_4 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_4);
inline constexpr int GVAR_WATER_CHIP_5 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_5);
inline constexpr int GVAR_WATER_CHIP_6 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_6);
inline constexpr int GVAR_WATER_CHIP_7 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_7);
inline constexpr int GVAR_WATER_CHIP_8 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_8);
inline constexpr int GVAR_WATER_CHIP_9 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_9);
inline constexpr int GVAR_WATER_CHIP_10 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_10);
inline constexpr int GVAR_WATER_CHIP_11 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_11);
inline constexpr int GVAR_WATER_CHIP_12 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_12);
inline constexpr int GVAR_WATER_CHIP_13 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_13);
inline constexpr int GVAR_WATER_CHIP_14 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_14);
inline constexpr int GVAR_WATER_CHIP_15 = static_cast<int>(GameGlobalVar::GVAR_WATER_CHIP_15);
inline constexpr int GVAR_DESTROY_VATS_1 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_1);
inline constexpr int GVAR_DESTROY_VATS_2 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_2);
inline constexpr int GVAR_DESTROY_VATS_3 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_3);
inline constexpr int GVAR_DESTROY_VATS_4 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_4);
inline constexpr int GVAR_DESTROY_VATS_5 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_5);
inline constexpr int GVAR_DESTROY_VATS_6 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_6);
inline constexpr int GVAR_DESTROY_VATS_7 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_7);
inline constexpr int GVAR_DESTROY_VATS_8 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_8);
inline constexpr int GVAR_DESTROY_VATS_9 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_9);
inline constexpr int GVAR_DESTROY_VATS_10 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_10);
inline constexpr int GVAR_DESTROY_VATS_11 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_11);
inline constexpr int GVAR_DESTROY_VATS_12 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_12);
inline constexpr int GVAR_DESTROY_VATS_13 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_13);
inline constexpr int GVAR_DESTROY_VATS_14 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_14);
inline constexpr int GVAR_DESTROY_VATS_15 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_VATS_15);
inline constexpr int GVAR_WATER_THIEF_1 = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF_1);
inline constexpr int GVAR_WATER_THIEF_2 = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF_2);
inline constexpr int GVAR_WATER_THIEF_3 = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF_3);
inline constexpr int GVAR_WATER_THIEF_4 = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF_4);
inline constexpr int GVAR_WATER_THIEF_5 = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF_5);
inline constexpr int GVAR_WATER_THIEF_6 = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF_6);
inline constexpr int GVAR_WATER_THIEF_7 = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF_7);
inline constexpr int GVAR_WATER_THIEF_8 = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF_8);
inline constexpr int GVAR_WATER_THIEF_9 = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF_9);
inline constexpr int GVAR_WATER_THIEF_10 = static_cast<int>(GameGlobalVar::GVAR_WATER_THIEF_10);
inline constexpr int GVAR_CALM_REBELS_1 = static_cast<int>(GameGlobalVar::GVAR_CALM_REBELS_1);
inline constexpr int GVAR_CALM_REBELS_2 = static_cast<int>(GameGlobalVar::GVAR_CALM_REBELS_2);
inline constexpr int GVAR_CALM_REBELS_3 = static_cast<int>(GameGlobalVar::GVAR_CALM_REBELS_3);
inline constexpr int GVAR_CALM_REBELS_4 = static_cast<int>(GameGlobalVar::GVAR_CALM_REBELS_4);
inline constexpr int GVAR_CALM_REBELS_5 = static_cast<int>(GameGlobalVar::GVAR_CALM_REBELS_5);
inline constexpr int GVAR_CALM_REBELS_6 = static_cast<int>(GameGlobalVar::GVAR_CALM_REBELS_6);
inline constexpr int GVAR_CALM_REBELS_7 = static_cast<int>(GameGlobalVar::GVAR_CALM_REBELS_7);
inline constexpr int GVAR_DESTROY_MASTER_1 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_1);
inline constexpr int GVAR_DESTROY_MASTER_2 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_2);
inline constexpr int GVAR_DESTROY_MASTER_3 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_3);
inline constexpr int GVAR_DESTROY_MASTER_4 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_4);
inline constexpr int GVAR_DESTROY_MASTER_5 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_5);
inline constexpr int GVAR_DESTROY_MASTER_6 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_6);
inline constexpr int GVAR_DESTROY_MASTER_7 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_7);
inline constexpr int GVAR_DESTROY_MASTER_8 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_8);
inline constexpr int GVAR_DESTROY_MASTER_9 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_9);
inline constexpr int GVAR_DESTROY_MASTER_10 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_10);
inline constexpr int GVAR_DESTROY_MASTER_11 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_11);
inline constexpr int GVAR_DESTROY_MASTER_12 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_12);
inline constexpr int GVAR_DESTROY_MASTER_13 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_13);
inline constexpr int GVAR_DESTROY_MASTER_14 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_14);
inline constexpr int GVAR_DESTROY_MASTER_15 = static_cast<int>(GameGlobalVar::GVAR_DESTROY_MASTER_15);
inline constexpr int GVAR_STOP_SCORPIONS_1 = static_cast<int>(GameGlobalVar::GVAR_STOP_SCORPIONS_1);
inline constexpr int GVAR_STOP_SCORPIONS_2 = static_cast<int>(GameGlobalVar::GVAR_STOP_SCORPIONS_2);
inline constexpr int GVAR_STOP_SCORPIONS_3 = static_cast<int>(GameGlobalVar::GVAR_STOP_SCORPIONS_3);
inline constexpr int GVAR_STOP_SCORPIONS_4 = static_cast<int>(GameGlobalVar::GVAR_STOP_SCORPIONS_4);
inline constexpr int GVAR_STOP_SCORPIONS_5 = static_cast<int>(GameGlobalVar::GVAR_STOP_SCORPIONS_5);
inline constexpr int GVAR_STOP_SCORPIONS_6 = static_cast<int>(GameGlobalVar::GVAR_STOP_SCORPIONS_6);
inline constexpr int GVAR_STOP_SCORPIONS_7 = static_cast<int>(GameGlobalVar::GVAR_STOP_SCORPIONS_7);
inline constexpr int GVAR_STOP_SCORPIONS_8 = static_cast<int>(GameGlobalVar::GVAR_STOP_SCORPIONS_8);
inline constexpr int GVAR_STOP_SCORPIONS_9 = static_cast<int>(GameGlobalVar::GVAR_STOP_SCORPIONS_9);
inline constexpr int GVAR_STOP_SCORPIONS_10 = static_cast<int>(GameGlobalVar::GVAR_STOP_SCORPIONS_10);
inline constexpr int GVAR_SAVE_TANDI_1 = static_cast<int>(GameGlobalVar::GVAR_SAVE_TANDI_1);
inline constexpr int GVAR_SAVE_TANDI_2 = static_cast<int>(GameGlobalVar::GVAR_SAVE_TANDI_2);
inline constexpr int GVAR_SAVE_TANDI_3 = static_cast<int>(GameGlobalVar::GVAR_SAVE_TANDI_3);
inline constexpr int GVAR_SAVE_TANDI_4 = static_cast<int>(GameGlobalVar::GVAR_SAVE_TANDI_4);
inline constexpr int GVAR_SAVE_TANDI_5 = static_cast<int>(GameGlobalVar::GVAR_SAVE_TANDI_5);
inline constexpr int GVAR_SAVE_TANDI_6 = static_cast<int>(GameGlobalVar::GVAR_SAVE_TANDI_6);
inline constexpr int GVAR_SAVE_TANDI_7 = static_cast<int>(GameGlobalVar::GVAR_SAVE_TANDI_7);
inline constexpr int GVAR_SAVE_TANDI_8 = static_cast<int>(GameGlobalVar::GVAR_SAVE_TANDI_8);
inline constexpr int GVAR_SAVE_TANDI_9 = static_cast<int>(GameGlobalVar::GVAR_SAVE_TANDI_9);
inline constexpr int GVAR_SAVE_TANDI_10 = static_cast<int>(GameGlobalVar::GVAR_SAVE_TANDI_10);
inline constexpr int GVAR_CURE_JARVIS_1 = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS_1);
inline constexpr int GVAR_CURE_JARVIS_2 = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS_2);
inline constexpr int GVAR_CURE_JARVIS_3 = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS_3);
inline constexpr int GVAR_CURE_JARVIS_4 = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS_4);
inline constexpr int GVAR_CURE_JARVIS_5 = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS_5);
inline constexpr int GVAR_CURE_JARVIS_6 = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS_6);
inline constexpr int GVAR_CURE_JARVIS_7 = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS_7);
inline constexpr int GVAR_CURE_JARVIS_8 = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS_8);
inline constexpr int GVAR_CURE_JARVIS_9 = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS_9);
inline constexpr int GVAR_CURE_JARVIS_10 = static_cast<int>(GameGlobalVar::GVAR_CURE_JARVIS_10);
inline constexpr int GVAR_MAKE_ANTIDOTE_1 = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE_1);
inline constexpr int GVAR_MAKE_ANTIDOTE_2 = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE_2);
inline constexpr int GVAR_MAKE_ANTIDOTE_3 = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE_3);
inline constexpr int GVAR_MAKE_ANTIDOTE_4 = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE_4);
inline constexpr int GVAR_MAKE_ANTIDOTE_5 = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE_5);
inline constexpr int GVAR_MAKE_ANTIDOTE_6 = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE_6);
inline constexpr int GVAR_MAKE_ANTIDOTE_7 = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE_7);
inline constexpr int GVAR_MAKE_ANTIDOTE_8 = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE_8);
inline constexpr int GVAR_MAKE_ANTIDOTE_9 = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE_9);
inline constexpr int GVAR_MAKE_ANTIDOTE_10 = static_cast<int>(GameGlobalVar::GVAR_MAKE_ANTIDOTE_10);
inline constexpr int GVAR_KILL_MUTANTS_1 = static_cast<int>(GameGlobalVar::GVAR_KILL_MUTANTS_1);
inline constexpr int GVAR_KILL_MUTANTS_2 = static_cast<int>(GameGlobalVar::GVAR_KILL_MUTANTS_2);
inline constexpr int GVAR_KILL_MUTANTS_3 = static_cast<int>(GameGlobalVar::GVAR_KILL_MUTANTS_3);
inline constexpr int GVAR_KILL_MUTANTS_4 = static_cast<int>(GameGlobalVar::GVAR_KILL_MUTANTS_4);
inline constexpr int GVAR_KILL_MUTANTS_5 = static_cast<int>(GameGlobalVar::GVAR_KILL_MUTANTS_5);
inline constexpr int GVAR_KILL_MUTANTS_6 = static_cast<int>(GameGlobalVar::GVAR_KILL_MUTANTS_6);
inline constexpr int GVAR_KILL_MUTANTS_7 = static_cast<int>(GameGlobalVar::GVAR_KILL_MUTANTS_7);
inline constexpr int GVAR_KILL_MUTANTS_8 = static_cast<int>(GameGlobalVar::GVAR_KILL_MUTANTS_8);
inline constexpr int GVAR_KILL_MUTANTS_9 = static_cast<int>(GameGlobalVar::GVAR_KILL_MUTANTS_9);
inline constexpr int GVAR_KILL_MUTANTS_10 = static_cast<int>(GameGlobalVar::GVAR_KILL_MUTANTS_10);
inline constexpr int GVAR_FIX_NECROP_PUMP_1 = static_cast<int>(GameGlobalVar::GVAR_FIX_NECROP_PUMP_1);
inline constexpr int GVAR_FIX_NECROP_PUMP_2 = static_cast<int>(GameGlobalVar::GVAR_FIX_NECROP_PUMP_2);
inline constexpr int GVAR_FIX_NECROP_PUMP_3 = static_cast<int>(GameGlobalVar::GVAR_FIX_NECROP_PUMP_3);
inline constexpr int GVAR_FIX_NECROP_PUMP_4 = static_cast<int>(GameGlobalVar::GVAR_FIX_NECROP_PUMP_4);
inline constexpr int GVAR_FIX_NECROP_PUMP_5 = static_cast<int>(GameGlobalVar::GVAR_FIX_NECROP_PUMP_5);
inline constexpr int GVAR_FIX_NECROP_PUMP_6 = static_cast<int>(GameGlobalVar::GVAR_FIX_NECROP_PUMP_6);
inline constexpr int GVAR_FIX_NECROP_PUMP_7 = static_cast<int>(GameGlobalVar::GVAR_FIX_NECROP_PUMP_7);
inline constexpr int GVAR_FIX_NECROP_PUMP_8 = static_cast<int>(GameGlobalVar::GVAR_FIX_NECROP_PUMP_8);
inline constexpr int GVAR_FIX_NECROP_PUMP_9 = static_cast<int>(GameGlobalVar::GVAR_FIX_NECROP_PUMP_9);
inline constexpr int GVAR_FIX_NECROP_PUMP_10 = static_cast<int>(GameGlobalVar::GVAR_FIX_NECROP_PUMP_10);
inline constexpr int GVAR_KILL_KILLIAN_1 = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN_1);
inline constexpr int GVAR_KILL_KILLIAN_2 = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN_2);
inline constexpr int GVAR_KILL_KILLIAN_3 = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN_3);
inline constexpr int GVAR_KILL_KILLIAN_4 = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN_4);
inline constexpr int GVAR_KILL_KILLIAN_5 = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN_5);
inline constexpr int GVAR_KILL_KILLIAN_6 = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN_6);
inline constexpr int GVAR_KILL_KILLIAN_7 = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN_7);
inline constexpr int GVAR_KILL_KILLIAN_8 = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN_8);
inline constexpr int GVAR_KILL_KILLIAN_9 = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN_9);
inline constexpr int GVAR_KILL_KILLIAN_10 = static_cast<int>(GameGlobalVar::GVAR_KILL_KILLIAN_10);
inline constexpr int GVAR_STOP_GIZMO_1 = static_cast<int>(GameGlobalVar::GVAR_STOP_GIZMO_1);
inline constexpr int GVAR_STOP_GIZMO_2 = static_cast<int>(GameGlobalVar::GVAR_STOP_GIZMO_2);
inline constexpr int GVAR_STOP_GIZMO_3 = static_cast<int>(GameGlobalVar::GVAR_STOP_GIZMO_3);
inline constexpr int GVAR_STOP_GIZMO_4 = static_cast<int>(GameGlobalVar::GVAR_STOP_GIZMO_4);
inline constexpr int GVAR_STOP_GIZMO_5 = static_cast<int>(GameGlobalVar::GVAR_STOP_GIZMO_5);
inline constexpr int GVAR_STOP_GIZMO_6 = static_cast<int>(GameGlobalVar::GVAR_STOP_GIZMO_6);
inline constexpr int GVAR_STOP_GIZMO_7 = static_cast<int>(GameGlobalVar::GVAR_STOP_GIZMO_7);
inline constexpr int GVAR_STOP_GIZMO_8 = static_cast<int>(GameGlobalVar::GVAR_STOP_GIZMO_8);
inline constexpr int GVAR_STOP_GIZMO_9 = static_cast<int>(GameGlobalVar::GVAR_STOP_GIZMO_9);
inline constexpr int GVAR_STOP_GIZMO_10 = static_cast<int>(GameGlobalVar::GVAR_STOP_GIZMO_10);
inline constexpr int GVAR_SAVE_SINTHIA_1 = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA_1);
inline constexpr int GVAR_SAVE_SINTHIA_2 = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA_2);
inline constexpr int GVAR_SAVE_SINTHIA_3 = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA_3);
inline constexpr int GVAR_SAVE_SINTHIA_4 = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA_4);
inline constexpr int GVAR_SAVE_SINTHIA_5 = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA_5);
inline constexpr int GVAR_SAVE_SINTHIA_6 = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA_6);
inline constexpr int GVAR_SAVE_SINTHIA_7 = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA_7);
inline constexpr int GVAR_SAVE_SINTHIA_8 = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA_8);
inline constexpr int GVAR_SAVE_SINTHIA_9 = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA_9);
inline constexpr int GVAR_SAVE_SINTHIA_10 = static_cast<int>(GameGlobalVar::GVAR_SAVE_SINTHIA_10);
inline constexpr int GVAR_TRISH_QUEST_1 = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST_1);
inline constexpr int GVAR_TRISH_QUEST_2 = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST_2);
inline constexpr int GVAR_TRISH_QUEST_3 = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST_3);
inline constexpr int GVAR_TRISH_QUEST_4 = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST_4);
inline constexpr int GVAR_TRISH_QUEST_5 = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST_5);
inline constexpr int GVAR_TRISH_QUEST_6 = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST_6);
inline constexpr int GVAR_TRISH_QUEST_7 = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST_7);
inline constexpr int GVAR_TRISH_QUEST_8 = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST_8);
inline constexpr int GVAR_TRISH_QUEST_9 = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST_9);
inline constexpr int GVAR_TRISH_QUEST_10 = static_cast<int>(GameGlobalVar::GVAR_TRISH_QUEST_10);
inline constexpr int GVAR_SAUL_QUEST_1 = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST_1);
inline constexpr int GVAR_SAUL_QUEST_2 = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST_2);
inline constexpr int GVAR_SAUL_QUEST_3 = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST_3);
inline constexpr int GVAR_SAUL_QUEST_4 = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST_4);
inline constexpr int GVAR_SAUL_QUEST_5 = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST_5);
inline constexpr int GVAR_SAUL_QUEST_6 = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST_6);
inline constexpr int GVAR_SAUL_QUEST_7 = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST_7);
inline constexpr int GVAR_SAUL_QUEST_8 = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST_8);
inline constexpr int GVAR_SAUL_QUEST_9 = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST_9);
inline constexpr int GVAR_SAUL_QUEST_10 = static_cast<int>(GameGlobalVar::GVAR_SAUL_QUEST_10);
inline constexpr int GVAR_STEAL_NECKLACE_1 = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE_1);
inline constexpr int GVAR_STEAL_NECKLACE_2 = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE_2);
inline constexpr int GVAR_STEAL_NECKLACE_3 = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE_3);
inline constexpr int GVAR_STEAL_NECKLACE_4 = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE_4);
inline constexpr int GVAR_STEAL_NECKLACE_5 = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE_5);
inline constexpr int GVAR_STEAL_NECKLACE_6 = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE_6);
inline constexpr int GVAR_STEAL_NECKLACE_7 = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE_7);
inline constexpr int GVAR_STEAL_NECKLACE_8 = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE_8);
inline constexpr int GVAR_STEAL_NECKLACE_9 = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE_9);
inline constexpr int GVAR_STEAL_NECKLACE_10 = static_cast<int>(GameGlobalVar::GVAR_STEAL_NECKLACE_10);
inline constexpr int GVAR_KILL_JAIN_1 = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN_1);
inline constexpr int GVAR_KILL_JAIN_2 = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN_2);
inline constexpr int GVAR_KILL_JAIN_3 = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN_3);
inline constexpr int GVAR_KILL_JAIN_4 = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN_4);
inline constexpr int GVAR_KILL_JAIN_5 = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN_5);
inline constexpr int GVAR_KILL_JAIN_6 = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN_6);
inline constexpr int GVAR_KILL_JAIN_7 = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN_7);
inline constexpr int GVAR_KILL_JAIN_8 = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN_8);
inline constexpr int GVAR_KILL_JAIN_9 = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN_9);
inline constexpr int GVAR_KILL_JAIN_10 = static_cast<int>(GameGlobalVar::GVAR_KILL_JAIN_10);
inline constexpr int GVAR_KILL_MERCHANT_1 = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT_1);
inline constexpr int GVAR_KILL_MERCHANT_2 = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT_2);
inline constexpr int GVAR_KILL_MERCHANT_3 = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT_3);
inline constexpr int GVAR_KILL_MERCHANT_4 = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT_4);
inline constexpr int GVAR_KILL_MERCHANT_5 = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT_5);
inline constexpr int GVAR_KILL_MERCHANT_6 = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT_6);
inline constexpr int GVAR_KILL_MERCHANT_7 = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT_7);
inline constexpr int GVAR_KILL_MERCHANT_8 = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT_8);
inline constexpr int GVAR_KILL_MERCHANT_9 = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT_9);
inline constexpr int GVAR_KILL_MERCHANT_10 = static_cast<int>(GameGlobalVar::GVAR_KILL_MERCHANT_10);
inline constexpr int GVAR_DEATHCLAW_SEED_1 = static_cast<int>(GameGlobalVar::GVAR_DEATHCLAW_SEED_1);
inline constexpr int GVAR_DEATHCLAW_SEED_2 = static_cast<int>(GameGlobalVar::GVAR_DEATHCLAW_SEED_2);
inline constexpr int GVAR_DEATHCLAW_SEED_3 = static_cast<int>(GameGlobalVar::GVAR_DEATHCLAW_SEED_3);
inline constexpr int GVAR_DEATHCLAW_SEED_4 = static_cast<int>(GameGlobalVar::GVAR_DEATHCLAW_SEED_4);
inline constexpr int GVAR_DEATHCLAW_SEED_5 = static_cast<int>(GameGlobalVar::GVAR_DEATHCLAW_SEED_5);
inline constexpr int GVAR_DEATHCLAW_SEED_6 = static_cast<int>(GameGlobalVar::GVAR_DEATHCLAW_SEED_6);
inline constexpr int GVAR_DEATHCLAW_SEED_7 = static_cast<int>(GameGlobalVar::GVAR_DEATHCLAW_SEED_7);
inline constexpr int GVAR_DEATHCLAW_SEED_8 = static_cast<int>(GameGlobalVar::GVAR_DEATHCLAW_SEED_8);
inline constexpr int GVAR_DEATHCLAW_SEED_9 = static_cast<int>(GameGlobalVar::GVAR_DEATHCLAW_SEED_9);
inline constexpr int GVAR_FRY_DEAD = static_cast<int>(GameGlobalVar::GVAR_FRY_DEAD);
inline constexpr int GVAR_MISSING_CARAVAN_1 = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN_1);
inline constexpr int GVAR_MISSING_CARAVAN_2 = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN_2);
inline constexpr int GVAR_MISSING_CARAVAN_3 = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN_3);
inline constexpr int GVAR_MISSING_CARAVAN_4 = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN_4);
inline constexpr int GVAR_MISSING_CARAVAN_5 = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN_5);
inline constexpr int GVAR_MISSING_CARAVAN_6 = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN_6);
inline constexpr int GVAR_MISSING_CARAVAN_7 = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN_7);
inline constexpr int GVAR_MISSING_CARAVAN_8 = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN_8);
inline constexpr int GVAR_MISSING_CARAVAN_9 = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN_9);
inline constexpr int GVAR_MISSING_CARAVAN_10 = static_cast<int>(GameGlobalVar::GVAR_MISSING_CARAVAN_10);
inline constexpr int GVAR_BECOME_INITIATE_1 = static_cast<int>(GameGlobalVar::GVAR_BECOME_INITIATE_1);
inline constexpr int GVAR_BECOME_INITIATE_2 = static_cast<int>(GameGlobalVar::GVAR_BECOME_INITIATE_2);
inline constexpr int GVAR_BECOME_INITIATE_3 = static_cast<int>(GameGlobalVar::GVAR_BECOME_INITIATE_3);
inline constexpr int GVAR_BECOME_INITIATE_4 = static_cast<int>(GameGlobalVar::GVAR_BECOME_INITIATE_4);
inline constexpr int GVAR_BECOME_INITIATE_5 = static_cast<int>(GameGlobalVar::GVAR_BECOME_INITIATE_5);
inline constexpr int GVAR_BECOME_INITIATE_6 = static_cast<int>(GameGlobalVar::GVAR_BECOME_INITIATE_6);
inline constexpr int GVAR_BECOME_INITIATE_7 = static_cast<int>(GameGlobalVar::GVAR_BECOME_INITIATE_7);
inline constexpr int GVAR_BECOME_INITIATE_8 = static_cast<int>(GameGlobalVar::GVAR_BECOME_INITIATE_8);
inline constexpr int GVAR_BECOME_INITIATE_9 = static_cast<int>(GameGlobalVar::GVAR_BECOME_INITIATE_9);
inline constexpr int GVAR_BECOME_INITIATE_10 = static_cast<int>(GameGlobalVar::GVAR_BECOME_INITIATE_10);
inline constexpr int GVAR_FIND_INITIATE_1 = static_cast<int>(GameGlobalVar::GVAR_FIND_INITIATE_1);
inline constexpr int GVAR_FIND_INITIATE_2 = static_cast<int>(GameGlobalVar::GVAR_FIND_INITIATE_2);
inline constexpr int GVAR_FIND_INITIATE_3 = static_cast<int>(GameGlobalVar::GVAR_FIND_INITIATE_3);
inline constexpr int GVAR_FIND_INITIATE_4 = static_cast<int>(GameGlobalVar::GVAR_FIND_INITIATE_4);
inline constexpr int GVAR_FIND_INITIATE_5 = static_cast<int>(GameGlobalVar::GVAR_FIND_INITIATE_5);
inline constexpr int GVAR_FIND_INITIATE_6 = static_cast<int>(GameGlobalVar::GVAR_FIND_INITIATE_6);
inline constexpr int GVAR_FIND_INITIATE_7 = static_cast<int>(GameGlobalVar::GVAR_FIND_INITIATE_7);
inline constexpr int GVAR_FIND_INITIATE_8 = static_cast<int>(GameGlobalVar::GVAR_FIND_INITIATE_8);
inline constexpr int GVAR_FIND_INITIATE_9 = static_cast<int>(GameGlobalVar::GVAR_FIND_INITIATE_9);
inline constexpr int GVAR_FIND_INITIATE_10 = static_cast<int>(GameGlobalVar::GVAR_FIND_INITIATE_10);
inline constexpr int GVAR_ROMEO_JULIET_1 = static_cast<int>(GameGlobalVar::GVAR_ROMEO_JULIET_1);
inline constexpr int GVAR_STOP_GANGS_1 = static_cast<int>(GameGlobalVar::GVAR_STOP_GANGS_1);
inline constexpr int GVAR_STOP_GANGS_2 = static_cast<int>(GameGlobalVar::GVAR_STOP_GANGS_2);
inline constexpr int GVAR_STOP_GANGS_3 = static_cast<int>(GameGlobalVar::GVAR_STOP_GANGS_3);
inline constexpr int GVAR_STOP_GANGS_4 = static_cast<int>(GameGlobalVar::GVAR_STOP_GANGS_4);
inline constexpr int GVAR_STOP_GANGS_5 = static_cast<int>(GameGlobalVar::GVAR_STOP_GANGS_5);
inline constexpr int GVAR_STOP_GANGS_6 = static_cast<int>(GameGlobalVar::GVAR_STOP_GANGS_6);
inline constexpr int GVAR_STOP_GANGS_7 = static_cast<int>(GameGlobalVar::GVAR_STOP_GANGS_7);
inline constexpr int GVAR_STOP_GANGS_8 = static_cast<int>(GameGlobalVar::GVAR_STOP_GANGS_8);
inline constexpr int GVAR_STOP_GANGS_9 = static_cast<int>(GameGlobalVar::GVAR_STOP_GANGS_9);
inline constexpr int GVAR_CATCH_SPY_1 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_1);
inline constexpr int GVAR_CATCH_SPY_2 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_2);
inline constexpr int GVAR_CATCH_SPY_3 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_3);
inline constexpr int GVAR_CATCH_SPY_4 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_4);
inline constexpr int GVAR_CATCH_SPY_5 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_5);
inline constexpr int GVAR_CATCH_SPY_6 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_6);
inline constexpr int GVAR_CATCH_SPY_7 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_7);
inline constexpr int GVAR_CATCH_SPY_8 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_8);
inline constexpr int GVAR_CATCH_SPY_9 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_9);
inline constexpr int GVAR_CATCH_SPY_10 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_10);
inline constexpr int GVAR_CATCH_SPY_11 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_11);
inline constexpr int GVAR_CATCH_SPY_12 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_12);
inline constexpr int GVAR_CATCH_SPY_13 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_13);
inline constexpr int GVAR_CATCH_SPY_14 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_14);
inline constexpr int GVAR_CATCH_SPY_15 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_15);
inline constexpr int GVAR_CATCH_SPY_16 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_16);
inline constexpr int GVAR_CATCH_SPY_17 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_17);
inline constexpr int GVAR_CATCH_SPY_18 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_18);
inline constexpr int GVAR_CATCH_SPY_19 = static_cast<int>(GameGlobalVar::GVAR_CATCH_SPY_19);
inline constexpr int GVAR_BECOME_BLADE_1 = static_cast<int>(GameGlobalVar::GVAR_BECOME_BLADE_1);
inline constexpr int GVAR_BECOME_BLADE_2 = static_cast<int>(GameGlobalVar::GVAR_BECOME_BLADE_2);
inline constexpr int GVAR_BECOME_BLADE_3 = static_cast<int>(GameGlobalVar::GVAR_BECOME_BLADE_3);
inline constexpr int GVAR_BECOME_BLADE_4 = static_cast<int>(GameGlobalVar::GVAR_BECOME_BLADE_4);
inline constexpr int GVAR_DELIVER_PACKAGE_1 = static_cast<int>(GameGlobalVar::GVAR_DELIVER_PACKAGE_1);
inline constexpr int GVAR_DELIVER_PACKAGE_2 = static_cast<int>(GameGlobalVar::GVAR_DELIVER_PACKAGE_2);
inline constexpr int GVAR_DELIVER_PACKAGE_3 = static_cast<int>(GameGlobalVar::GVAR_DELIVER_PACKAGE_3);
inline constexpr int GVAR_DELIVER_PACKAGE_4 = static_cast<int>(GameGlobalVar::GVAR_DELIVER_PACKAGE_4);
inline constexpr int GVAR_DELIVER_PACKAGE_5 = static_cast<int>(GameGlobalVar::GVAR_DELIVER_PACKAGE_5);
inline constexpr int GVAR_FIX_FARM_1 = static_cast<int>(GameGlobalVar::GVAR_FIX_FARM_1);
inline constexpr int GVAR_FIX_FARM_2 = static_cast<int>(GameGlobalVar::GVAR_FIX_FARM_2);
inline constexpr int GVAR_FIX_FARM_3 = static_cast<int>(GameGlobalVar::GVAR_FIX_FARM_3);
inline constexpr int GVAR_FIX_FARM_4 = static_cast<int>(GameGlobalVar::GVAR_FIX_FARM_4);
inline constexpr int GVAR_LOST_BROTHER_1 = static_cast<int>(GameGlobalVar::GVAR_LOST_BROTHER_1);
inline constexpr int GVAR_LOST_BROTHER_2 = static_cast<int>(GameGlobalVar::GVAR_LOST_BROTHER_2);
inline constexpr int GVAR_LOST_BROTHER_3 = static_cast<int>(GameGlobalVar::GVAR_LOST_BROTHER_3);
inline constexpr int GVAR_LOST_BROTHER_4 = static_cast<int>(GameGlobalVar::GVAR_LOST_BROTHER_4);
inline constexpr int GVAR_LOST_BROTHER_5 = static_cast<int>(GameGlobalVar::GVAR_LOST_BROTHER_5);
inline constexpr int GVAR_POWER_GLOW_1 = static_cast<int>(GameGlobalVar::GVAR_POWER_GLOW_1);
inline constexpr int GVAR_DISARM_TRAPS_1 = static_cast<int>(GameGlobalVar::GVAR_DISARM_TRAPS_1);
inline constexpr int GVAR_DISARM_TRAPS_2 = static_cast<int>(GameGlobalVar::GVAR_DISARM_TRAPS_2);
inline constexpr int GVAR_DISARM_TRAPS_3 = static_cast<int>(GameGlobalVar::GVAR_DISARM_TRAPS_3);
inline constexpr int GVAR_MAX_MUTANTS = static_cast<int>(GameGlobalVar::GVAR_MAX_MUTANTS);
inline constexpr int GVAR_TIME_CHIP_GONE = static_cast<int>(GameGlobalVar::GVAR_TIME_CHIP_GONE);
inline constexpr int GVAR_SET_DEAD = static_cast<int>(GameGlobalVar::GVAR_SET_DEAD);
inline constexpr int GVAR_MUTANTS_GONE = static_cast<int>(GameGlobalVar::GVAR_MUTANTS_GONE);
inline constexpr int GVAR_BUST_SKULZ = static_cast<int>(GameGlobalVar::GVAR_BUST_SKULZ);
inline constexpr int GVAR_SHERRY_TURNS = static_cast<int>(GameGlobalVar::GVAR_SHERRY_TURNS);
inline constexpr int GVAR_TRISH_STATUS = static_cast<int>(GameGlobalVar::GVAR_TRISH_STATUS);
inline constexpr int GVAR_MARK_V13_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_V13_1);
inline constexpr int GVAR_MARK_V13_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_V13_2);
inline constexpr int GVAR_MARK_V13_3 = static_cast<int>(GameGlobalVar::GVAR_MARK_V13_3);
inline constexpr int GVAR_MARK_V13_4 = static_cast<int>(GameGlobalVar::GVAR_MARK_V13_4);
inline constexpr int GVAR_MARK_V15_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_V15_1);
inline constexpr int GVAR_MARK_V15_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_V15_2);
inline constexpr int GVAR_MARK_V15_3 = static_cast<int>(GameGlobalVar::GVAR_MARK_V15_3);
inline constexpr int GVAR_MARK_V15_4 = static_cast<int>(GameGlobalVar::GVAR_MARK_V15_4);
inline constexpr int GVAR_MARK_SHADY_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_SHADY_1);
inline constexpr int GVAR_MARK_SHADY_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_SHADY_2);
inline constexpr int GVAR_MARK_SHADY_3 = static_cast<int>(GameGlobalVar::GVAR_MARK_SHADY_3);
inline constexpr int GVAR_MARK_JUNK_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_JUNK_1);
inline constexpr int GVAR_MARK_JUNK_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_JUNK_2);
inline constexpr int GVAR_MARK_JUNK_3 = static_cast<int>(GameGlobalVar::GVAR_MARK_JUNK_3);
inline constexpr int GVAR_MARK_RAIDERS_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_RAIDERS_1);
inline constexpr int GVAR_MARK_NECROP_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_NECROP_1);
inline constexpr int GVAR_MARK_NECROP_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_NECROP_2);
inline constexpr int GVAR_MARK_NECROP_3 = static_cast<int>(GameGlobalVar::GVAR_MARK_NECROP_3);
inline constexpr int GVAR_MARK_HUB_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_HUB_1);
inline constexpr int GVAR_MARK_HUB_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_HUB_2);
inline constexpr int GVAR_MARK_HUB_3 = static_cast<int>(GameGlobalVar::GVAR_MARK_HUB_3);
inline constexpr int GVAR_MARK_HUB_4 = static_cast<int>(GameGlobalVar::GVAR_MARK_HUB_4);
inline constexpr int GVAR_MARK_HUB_5 = static_cast<int>(GameGlobalVar::GVAR_MARK_HUB_5);
inline constexpr int GVAR_MARK_HUB_6 = static_cast<int>(GameGlobalVar::GVAR_MARK_HUB_6);
inline constexpr int GVAR_MARK_BROTHER_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_BROTHER_1);
inline constexpr int GVAR_MARK_BROTHER_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_BROTHER_2);
inline constexpr int GVAR_MARK_BROTHER_3 = static_cast<int>(GameGlobalVar::GVAR_MARK_BROTHER_3);
inline constexpr int GVAR_MARK_BROTHER_4 = static_cast<int>(GameGlobalVar::GVAR_MARK_BROTHER_4);
inline constexpr int GVAR_MARK_BROTHER_5 = static_cast<int>(GameGlobalVar::GVAR_MARK_BROTHER_5);
inline constexpr int GVAR_MARK_BASE_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_BASE_1);
inline constexpr int GVAR_MARK_BASE_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_BASE_2);
inline constexpr int GVAR_MARK_BASE_3 = static_cast<int>(GameGlobalVar::GVAR_MARK_BASE_3);
inline constexpr int GVAR_MARK_BASE_4 = static_cast<int>(GameGlobalVar::GVAR_MARK_BASE_4);
inline constexpr int GVAR_MARK_BASE_5 = static_cast<int>(GameGlobalVar::GVAR_MARK_BASE_5);
inline constexpr int GVAR_MARK_GLOW_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_GLOW_1);
inline constexpr int GVAR_MARK_GLOW_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_GLOW_2);
inline constexpr int GVAR_MARK_LA_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_LA_1);
inline constexpr int GVAR_MARK_LA_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_LA_2);
inline constexpr int GVAR_MARK_LA_3 = static_cast<int>(GameGlobalVar::GVAR_MARK_LA_3);
inline constexpr int GVAR_MARK_LA_4 = static_cast<int>(GameGlobalVar::GVAR_MARK_LA_4);
inline constexpr int GVAR_MARK_LA_5 = static_cast<int>(GameGlobalVar::GVAR_MARK_LA_5);
inline constexpr int GVAR_MARK_CHILD_1 = static_cast<int>(GameGlobalVar::GVAR_MARK_CHILD_1);
inline constexpr int GVAR_MARK_CHILD_2 = static_cast<int>(GameGlobalVar::GVAR_MARK_CHILD_2);
inline constexpr int GVAR_STRANGER_STATUS = static_cast<int>(GameGlobalVar::GVAR_STRANGER_STATUS);
inline constexpr int GVAR_GAME_DIFFICULTY = static_cast<int>(GameGlobalVar::GVAR_GAME_DIFFICULTY);
inline constexpr int GVAR_RUNNING_BURNING_GUY = static_cast<int>(GameGlobalVar::GVAR_RUNNING_BURNING_GUY);
inline constexpr int GVAR_ARADESH_STATUS = static_cast<int>(GameGlobalVar::GVAR_ARADESH_STATUS);
inline constexpr int GVAR_RHOMBUS_STATUS = static_cast<int>(GameGlobalVar::GVAR_RHOMBUS_STATUS);
inline constexpr int GVAR_KIND_TO_HAROLD = static_cast<int>(GameGlobalVar::GVAR_KIND_TO_HAROLD);
inline constexpr int GVAR_GARRET_STATUS = static_cast<int>(GameGlobalVar::GVAR_GARRET_STATUS);
inline constexpr int GVAR_RADIO_COMPUTER_OFF = static_cast<int>(GameGlobalVar::GVAR_RADIO_COMPUTER_OFF);
inline constexpr int GVAR_FORCE_FIELDS_OFF = static_cast<int>(GameGlobalVar::GVAR_FORCE_FIELDS_OFF);
inline constexpr int GVAR_FIELD_COMPUTER_MODIFIED = static_cast<int>(GameGlobalVar::GVAR_FIELD_COMPUTER_MODIFIED);
inline constexpr int GVAR_GARLS_FRIEND = static_cast<int>(GameGlobalVar::GVAR_GARLS_FRIEND);
inline constexpr int GVAR_ZIMMERMAN = static_cast<int>(GameGlobalVar::GVAR_ZIMMERMAN);
inline constexpr int GVAR_BLADES = static_cast<int>(GameGlobalVar::GVAR_BLADES);
inline constexpr int GVAR_GUN_RUNNER = static_cast<int>(GameGlobalVar::GVAR_GUN_RUNNER);
inline constexpr int GVAR_CHEMISTRY_BOOK = static_cast<int>(GameGlobalVar::GVAR_CHEMISTRY_BOOK);
inline constexpr int GVAR_ENEMY_REGULATOR = static_cast<int>(GameGlobalVar::GVAR_ENEMY_REGULATOR);
inline constexpr int GVAR_ENEMY_BLADE = static_cast<int>(GameGlobalVar::GVAR_ENEMY_BLADE);

} // namespace fallout

